project:
  type: book

book:
  title: "Introduction to Data Science"
  author: "Ethan Meyers"
  chapters:
    - index.qmd
    - introduction.qmd
    - python_basics.qmd
    - array_computations.qmd
    - data_tables.qmd
    - data_visualization.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      
  pdf:
    documentclass: scrreprt



