<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.11.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Array computations – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data_tables.html" rel="next">
<link href="./descriptive_stats_and_plots.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d5b4e69c7e37b49c6591bcc5116dd748.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3d497cff885f6278d37568d0ef0763f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./array_computations.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Array computations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Python basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats_and_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive statistics and plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./array_computations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Array computations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data tables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interactive_visualizations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Interactive visualizations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Maps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iteration_and_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Iteration and writing functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to statistical inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis_testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unsupervised_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Unsupervised learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Web data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./where_next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Where to go next</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setting_up_python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Setting up Python</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#why-arrays-instead-of-lists" id="toc-why-arrays-instead-of-lists" class="nav-link active" data-scroll-target="#why-arrays-instead-of-lists"><span class="header-section-number">4.1</span> Why arrays instead of lists?</a></li>
  <li><a href="#an-example-dataset-a-year-of-u.s.-gas-prices" id="toc-an-example-dataset-a-year-of-u.s.-gas-prices" class="nav-link" data-scroll-target="#an-example-dataset-a-year-of-u.s.-gas-prices"><span class="header-section-number">4.2</span> An example dataset: a year of U.S. gas prices</a></li>
  <li><a href="#creating-arrays-and-their-basic-properties" id="toc-creating-arrays-and-their-basic-properties" class="nav-link" data-scroll-target="#creating-arrays-and-their-basic-properties"><span class="header-section-number">4.3</span> Creating arrays and their basic properties</a></li>
  <li><a href="#indexing-and-slicing" id="toc-indexing-and-slicing" class="nav-link" data-scroll-target="#indexing-and-slicing"><span class="header-section-number">4.4</span> Indexing and slicing</a></li>
  <li><a href="#numpy-functions-for-summarizing-and-transforming-arrays" id="toc-numpy-functions-for-summarizing-and-transforming-arrays" class="nav-link" data-scroll-target="#numpy-functions-for-summarizing-and-transforming-arrays"><span class="header-section-number">4.5</span> NumPy functions for summarizing and transforming arrays</a>
  <ul class="collapse">
  <li><a href="#transforming-every-value-at-once" id="toc-transforming-every-value-at-once" class="nav-link" data-scroll-target="#transforming-every-value-at-once"><span class="header-section-number">4.5.1</span> Transforming every value at once</a></li>
  <li><a href="#summarizing-an-array-with-a-single-number" id="toc-summarizing-an-array-with-a-single-number" class="nav-link" data-scroll-target="#summarizing-an-array-with-a-single-number"><span class="header-section-number">4.5.2</span> Summarizing an array with a single number</a></li>
  <li><a href="#working-across-a-sequence" id="toc-working-across-a-sequence" class="nav-link" data-scroll-target="#working-across-a-sequence"><span class="header-section-number">4.5.3</span> Working across a sequence</a></li>
  </ul></li>
  <li><a href="#boolean-arrays-and-boolean-indexing" id="toc-boolean-arrays-and-boolean-indexing" class="nav-link" data-scroll-target="#boolean-arrays-and-boolean-indexing"><span class="header-section-number">4.6</span> Boolean arrays and Boolean indexing</a>
  <ul class="collapse">
  <li><a href="#boolean-indexing" id="toc-boolean-indexing" class="nav-link" data-scroll-target="#boolean-indexing"><span class="header-section-number">4.6.1</span> Boolean indexing</a></li>
  <li><a href="#the-same-idea-on-other-data" id="toc-the-same-idea-on-other-data" class="nav-link" data-scroll-target="#the-same-idea-on-other-data"><span class="header-section-number">4.6.2</span> The same idea on other data</a></li>
  </ul></li>
  <li><a href="#higher-dimensional-arrays-and-image-processing" id="toc-higher-dimensional-arrays-and-image-processing" class="nav-link" data-scroll-target="#higher-dimensional-arrays-and-image-processing"><span class="header-section-number">4.7</span> Higher-dimensional arrays and image processing</a>
  <ul class="collapse">
  <li><a href="#creating-and-indexing-matrices" id="toc-creating-and-indexing-matrices" class="nav-link" data-scroll-target="#creating-and-indexing-matrices"><span class="header-section-number">4.7.1</span> Creating and indexing matrices</a></li>
  <li><a href="#grayscale-images-are-2d-arrays" id="toc-grayscale-images-are-2d-arrays" class="nav-link" data-scroll-target="#grayscale-images-are-2d-arrays"><span class="header-section-number">4.7.2</span> Grayscale images are 2D arrays</a></li>
  <li><a href="#color-images-are-3d-arrays" id="toc-color-images-are-3d-arrays" class="nav-link" data-scroll-target="#color-images-are-3d-arrays"><span class="header-section-number">4.7.3</span> Color images are 3D arrays</a></li>
  <li><a href="#manipulating-an-image-is-just-array-computation" id="toc-manipulating-an-image-is-just-array-computation" class="nav-link" data-scroll-target="#manipulating-an-image-is-just-array-computation"><span class="header-section-number">4.7.4</span> Manipulating an image is just array computation</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.8</span> Summary</a></li>
  <li><a href="#code-summary" id="toc-code-summary" class="nav-link" data-scroll-target="#code-summary"><span class="header-section-number">4.9</span> Code summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">4.10</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-array-computations" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Array computations</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the previous chapter we stored data in plain Python lists, and we used the <code>statistics</code> module (and considerable manual work) to summarize it. That approach worked, but it was tedious. To do almost anything to <em>every</em> value in a list (add a tax to every price, convert every value to different units, or just add two lists of numbers together), we had to handle the values one at a time.</p>
<p>In this chapter we introduce <strong>NumPy</strong> (short for “Numerical Python”), the standard Python library for working with numerical data. NumPy gives us a new kind of container called an <strong>array</strong>, which makes numerical computations shorter to write and faster to run compared to using lists. Arrays are the foundation that nearly every other data science tool in Python, including the Pandas package we’ll use later, is built on top of.</p>
<p>By the end of this chapter you’ll be able to load numerical data into arrays, transform and summarize that data in a single step, filter it down to the values you care about, and even treat images as arrays of numbers.</p>
<section id="why-arrays-instead-of-lists" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="why-arrays-instead-of-lists"><span class="header-section-number">4.1</span> Why arrays instead of lists?</h2>
<p>To see some of the shortcomings of using lists for data processing, suppose we have the price of a gallon of gas (in dollars) for three weeks, stored in a list:</p>
<div id="b189d5e8" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>weekly_prices <span class="op">=</span> [<span class="fl">3.05</span>, <span class="fl">3.04</span>, <span class="fl">3.11</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now imagine the government adds a 100% tax, doubling the price of every gallon. If we wanted the new price for each week, it would be natural to <em>try</em> multiplying the list by 2, but lists don’t behave the way we might hope:</p>
<div id="e093a33d" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiplying a list by 2 repeats the list instead of doubling each value</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>weekly_prices <span class="op">*</span> <span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>[3.05, 3.04, 3.11, 3.05, 3.04, 3.11]</code></pre>
</div>
</div>
<p>As you can see, that doesn’t double each price. Instead, multiplying a list by a number just <em>repeats</em> the list. And if we wanted to <em>add</em> a constant to each item, writing <code>weekly_prices + 2</code> would produce an error rather than the new prices. To actually double each price we would have to reach into the list and update each value individually:</p>
<div id="6f0d6c3c" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Doubling each price, one value at a time</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>[weekly_prices[<span class="dv">0</span>] <span class="op">*</span> <span class="dv">2</span>, weekly_prices[<span class="dv">1</span>] <span class="op">*</span> <span class="dv">2</span>, weekly_prices[<span class="dv">2</span>] <span class="op">*</span> <span class="dv">2</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>[6.1, 6.08, 6.22]</code></pre>
</div>
</div>
<p>This works for three prices, but it would be impractical for a larger dataset.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Python does have a tool for repeating an action many times without writing it out by hand: the <strong>loop</strong>, which we cover later in <a href="iteration_and_functions.html" class="quarto-xref"><span>Chapter 9</span></a>. But for the whole-dataset calculations that are common in data science, the array approach shown in this chapter is usually shorter and easier to read, so we will favor it throughout the book.</p>
</div>
</div>
<p>NumPy lets us express the same computation in one line. First, import the library (by near-universal convention, NumPy is imported under the short name <code>np</code>):</p>
<div id="548d81f4" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now we can turn our list into a NumPy array with <code>np.array()</code> and multiply by 2:</p>
<div id="3b1bd564" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>price_array <span class="op">=</span> np.array([<span class="fl">3.05</span>, <span class="fl">3.04</span>, <span class="fl">3.11</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Doubling the gas prices</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>price_array <span class="op">*</span> <span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>array([6.1 , 6.08, 6.22])</code></pre>
</div>
</div>
<p>The operation was applied to every element automatically. This idea, applying an operation to every element of an array at once, is called <strong>vectorization</strong>, and it is what makes NumPy so useful. Compared to lists, arrays give us two main advantages:</p>
<ol type="1">
<li><strong>Ease of expression.</strong> Element-wise arithmetic like <code>price_array * 2</code> and <code>price_array + 2</code> lets us say what we mean in a single short expression.</li>
<li><strong>Speed.</strong> NumPy performs these operations in fast, pre-compiled code and stores values more compactly than a list, so computations on large arrays run faster and use less memory.</li>
</ol>
<div id="exercise-array_computations-vectorize" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here are three more weekly gas prices stored in a list: <code>[3.20, 3.15, 3.18]</code>. Turn this list into a NumPy array, then use a single expression (no loop) to calculate the prices with a three-dollar surcharge added to each (i.e., each price becomes 3 dollars higher).</p>
</div>
</div>
<div id="solution-array_computations-vectorize" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="634da973" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>more_prices <span class="op">=</span> np.array([<span class="fl">3.20</span>, <span class="fl">3.15</span>, <span class="fl">3.18</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding 3 dollars to every price at once</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>more_prices <span class="op">+</span> <span class="dv">3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>array([6.2 , 6.15, 6.18])</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="an-example-dataset-a-year-of-u.s.-gas-prices" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="an-example-dataset-a-year-of-u.s.-gas-prices"><span class="header-section-number">4.2</span> An example dataset: a year of U.S. gas prices</h2>
<p>To explore NumPy we’ll look at the price of gasoline in the United States over the course of a year. Gas prices change every week, so the data gives us a natural sequence to explore: how prices moved, how much they varied, and what fraction of weeks fell below a given threshold.</p>
<p>Our data comes from <strong>FRED</strong> (Federal Reserve Economic Data), a large public database of economic time series maintained by the Federal Reserve Bank of St.&nbsp;Louis. We’ll store the U.S. average weekly retail price of regular gasoline for 2025 in two NumPy arrays: <code>gas_prices</code>, which holds the price for each week, and <code>gas_dates</code>, which holds the corresponding date. Run the cell below to load the data; as with the data-loading code in the previous chapter, you don’t need to understand its details yet.</p>
<div id="52942e11" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Try to download the data live from FRED; if that fails (for example, when there</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># is no internet connection), fall back to a saved snapshot of the same year.</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="im">from</span> pandas_datareader.fred <span class="im">import</span> FredReader</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    gas_data_all <span class="op">=</span> FredReader(<span class="st">"GASREGW"</span>, start<span class="op">=</span><span class="st">"2024-06-01"</span>, end<span class="op">=</span><span class="st">"2026-01-15"</span>).read().reset_index()</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    gas_year <span class="op">=</span> gas_data_all[(gas_data_all[<span class="st">"DATE"</span>] <span class="op">&gt;=</span> <span class="st">"2025-01-01"</span>) <span class="op">&amp;</span> (gas_data_all[<span class="st">"DATE"</span>] <span class="op">&lt;</span> <span class="st">"2026-01-01"</span>)]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span>:</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    gas_year <span class="op">=</span> pd.read_csv(<span class="st">"data/gas_prices_GASREGW_2025.csv"</span>, parse_dates<span class="op">=</span>[<span class="st">"DATE"</span>])</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull the prices and dates out of the data table as NumPy arrays</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>gas_prices <span class="op">=</span> gas_year[<span class="st">"GASREGW"</span>].values</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>gas_dates <span class="op">=</span> gas_year[<span class="st">"DATE"</span>].values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s take a look at the prices:</p>
<div id="d49a6dac" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>gas_prices</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>array([3.047, 3.043, 3.109, 3.103, 3.082, 3.128, 3.148, 3.125, 3.078,
       3.069, 3.058, 3.115, 3.162, 3.243, 3.168, 3.141, 3.133, 3.147,
       3.12 , 3.173, 3.16 , 3.127, 3.108, 3.139, 3.213, 3.164, 3.125,
       3.13 , 3.121, 3.123, 3.14 , 3.118, 3.125, 3.147, 3.177, 3.192,
       3.168, 3.173, 3.118, 3.124, 3.061, 3.019, 3.035, 3.019, 3.056,
       3.062, 3.061, 2.985, 2.94 , 2.895, 2.841, 2.811])</code></pre>
</div>
</div>
<p>This is an array of 52 numbers, one price per week. The first value, about $3.05, is the price in the first week of January. The matching <code>gas_dates</code> array holds the date of each week’s price, stored as NumPy datetime values:</p>
<div id="d01cfa45" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The dates of the first three weekly prices</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>gas_dates[<span class="dv">0</span>:<span class="dv">3</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array(['2025-01-06T00:00:00.000000', '2025-01-13T00:00:00.000000',
       '2025-01-20T00:00:00.000000'], dtype='datetime64[us]')</code></pre>
</div>
</div>
<p>Before computing any statistics, we can see the whole year at a glance using the Matplotlib skills from the previous chapter:</p>
<div id="8b81221d" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.plot(gas_dates, gas_prices, <span class="st">'.-'</span>)  <span class="co"># '.-' draws dots at each data point connected by lines</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Date"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Price per gallon ($)"</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"U.S. weekly regular gas price, 2025"</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-11-output-1.png" width="595" height="486" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Prices rose through the spring, peaked in April, and drifted lower through the second half of the year, reaching their lowest point in late December. Throughout the chapter we’ll use these two arrays, and NumPy, to ask more precise questions about this story.</p>
</section>
<section id="creating-arrays-and-their-basic-properties" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="creating-arrays-and-their-basic-properties"><span class="header-section-number">4.3</span> Creating arrays and their basic properties</h2>
<p>We’ve already seen the most common way to make an array: pass a list to <code>np.array()</code>. For example, we can pass the list <code>[10, 20, 30, 40]</code> to the <code>np.array()</code> function to create an array of 4 elements:</p>
<div id="185787b9" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>example_array <span class="op">=</span> np.array([<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">40</span>])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>example_array</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>array([10, 20, 30, 40])</code></pre>
</div>
</div>
<p>An important property of NumPy arrays is that all elements must have the <strong>same data type</strong>. For example, an array can hold all numbers or all Booleans, but unlike a list it cannot mix types.</p>
<p>To see what type of element is being stored in an array, we can access the array’s <code>dtype</code> attribute:</p>
<div id="1170d87f" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The data type of the elements (float64 means decimal numbers)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>gas_prices.dtype</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>dtype('float64')</code></pre>
</div>
</div>
<p>Note that we write <code>.dtype</code> <em>without</em> parentheses, because it is an <strong>attribute</strong> of the array (a stored property) rather than a function we call.</p>
<p>What happens if you break the same-type rule and pass <code>np.array()</code> a list with mixed types? NumPy does not report an error. Instead it silently converts every value to a common type, usually strings:</p>
<div id="7cc966b5" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>np.array([<span class="dv">1</span>, <span class="st">"two"</span>, <span class="va">True</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>array(['1', 'two', 'True'], dtype='&lt;U21')</code></pre>
</div>
</div>
<p>The quotes around each value show that everything, including the number and the Boolean, has become a string. Arithmetic will no longer work on this array, so an accidental string in a list of numbers is worth watching out for.</p>
<p>Similarly, we can see how an array’s elements are arranged using the <code>shape</code> attribute:</p>
<div id="40320822" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The shape of the array: 52 weeks of prices in a single dimension</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>gas_prices.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>(52,)</code></pre>
</div>
</div>
<p>The <code>.shape</code> is reported as <code>(52,)</code>, which tells us the array has 52 elements arranged in a single dimension. The trailing comma is Python’s notation for a one-element <strong>tuple</strong> (a parentheses-wrapped sequence of values); a 2D array would show two numbers here, like <code>(4, 5)</code>. Two more useful attributes are <code>.size</code> (the total number of elements) and <code>.ndim</code> (the number of dimensions):</p>
<div id="b72ac4e7" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>[gas_prices.size, gas_prices.ndim]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>[52, 1]</code></pre>
</div>
</div>
<p>Sometimes we want to change the data type of an array, for example to view our prices as whole numbers of dollars. The <code>.astype()</code> method makes a new array with a different type:</p>
<div id="b0e24357" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the decimal prices to integers (the decimal part is dropped, not rounded)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>gas_prices.astype(<span class="bu">int</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 2, 2, 2, 2, 2])</code></pre>
</div>
</div>
<p>Finally, NumPy can generate arrays for us without starting from a list. <code>np.arange()</code> allows us to create an array of sequential integers, and <code>np.linspace()</code> produces a given number of evenly spaced values between two endpoints:</p>
<div id="0e14d0bc" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Whole numbers from 0 up to (but not including) 10</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>np.arange(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])</code></pre>
</div>
</div>
<p><code>np.arange()</code> can also take a start and a stop value. Like slicing, the stop value is excluded:</p>
<div id="68323e9d" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Whole numbers from 1 up to (but not including) 11</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>np.arange(<span class="dv">1</span>, <span class="dv">11</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])</code></pre>
</div>
</div>
<div id="6d65d274" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Five evenly spaced values from 0 to 1</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>array([0.  , 0.25, 0.5 , 0.75, 1.  ])</code></pre>
</div>
</div>
<div id="exercise-array_computations-create" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>np.arange()</code> to create an array containing the whole numbers from 5 to 15 (including both endpoints). Then use <code>.astype()</code> to make a version of that array whose values are floating-point numbers, and check its <code>.dtype</code> to confirm the conversion worked.</p>
</div>
</div>
<div id="solution-array_computations-create" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="2d8c06a4" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The stop value is excluded, so we use 16 to include 15</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>nums <span class="op">=</span> np.arange(<span class="dv">5</span>, <span class="dv">16</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>nums_float <span class="op">=</span> nums.astype(<span class="bu">float</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>[nums_float, nums_float.dtype]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>[array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]),
 dtype('float64')]</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="indexing-and-slicing" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="indexing-and-slicing"><span class="header-section-number">4.4</span> Indexing and slicing</h2>
<p>Indexing and slicing arrays work just like they did for lists in the Python basics chapter. We use square brackets with a position (starting from 0), and we can use negative positions to count from the end:</p>
<div id="ba39158a" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The price in the first week of the year</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>gas_prices[<span class="dv">0</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>np.float64(3.047)</code></pre>
</div>
</div>
<div id="e637e358" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The price in the last week of the year</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>gas_prices[<span class="op">-</span><span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>np.float64(2.811)</code></pre>
</div>
</div>
<p>We can also take a <strong>slice</strong> to get a range of values. Here are the prices for the first five weeks:</p>
<div id="8d1b4adb" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>gas_prices[<span class="dv">0</span>:<span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>array([3.047, 3.043, 3.109, 3.103, 3.082])</code></pre>
</div>
</div>
<p>Right away we can see that gas started the year a little over $3.00 a gallon. To say more, we’ll want to summarize all 52 weeks at once.</p>
<div id="exercise-array_computations-slice" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use slicing to select and display the gas prices for the <em>last five weeks</em> of the year. (Hint: negative positions count from the end of the array.)</p>
</div>
</div>
<div id="solution-array_computations-slice" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="70166f34" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gas_prices[<span class="op">-</span><span class="dv">5</span>:]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>array([2.985, 2.94 , 2.895, 2.841, 2.811])</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="numpy-functions-for-summarizing-and-transforming-arrays" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="numpy-functions-for-summarizing-and-transforming-arrays"><span class="header-section-number">4.5</span> NumPy functions for summarizing and transforming arrays</h2>
<p>This is where arrays are most useful. NumPy provides a large collection of functions that operate on an entire array at once, letting us answer questions about our data with a single line of code. These fall into two families.</p>
<p>The first family transforms every value: arithmetic like <code>gas_prices * 147</code> applies the operation to each element. The second family reduces an array to a summary: <code>np.mean()</code>, <code>np.median()</code>, <code>np.min()</code>, <code>np.max()</code>, <code>np.sum()</code>, <code>np.std()</code>, and <code>np.percentile()</code> each collapse the whole array down to one number. You saw the <code>statistics</code> module handle some of these in the previous chapter; NumPy’s versions work directly on arrays and are much faster on large datasets.</p>
<section id="transforming-every-value-at-once" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="transforming-every-value-at-once"><span class="header-section-number">4.5.1</span> Transforming every value at once</h3>
<p>We saw earlier that we can do arithmetic on an entire array. Because each operation applies to every element, we can answer “what if” questions in a single line. For example, one U.S. dollar was worth roughly 147 Japanese yen during this period. So what was each week’s gas price in yen?</p>
<div id="e3ebfc26" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert every weekly price from dollars to yen</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>gas_prices <span class="op">*</span> <span class="dv">147</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>array([447.909, 447.321, 457.023, 456.141, 453.054, 459.816, 462.756,
       459.375, 452.466, 451.143, 449.526, 457.905, 464.814, 476.721,
       465.696, 461.727, 460.551, 462.609, 458.64 , 466.431, 464.52 ,
       459.669, 456.876, 461.433, 472.311, 465.108, 459.375, 460.11 ,
       458.787, 459.081, 461.58 , 458.346, 459.375, 462.609, 467.019,
       469.224, 465.696, 466.431, 458.346, 459.228, 449.967, 443.793,
       446.145, 443.793, 449.232, 450.114, 449.967, 438.795, 432.18 ,
       425.565, 417.627, 413.217])</code></pre>
</div>
</div>
<p>Or, returning to our tax example, what would each price be with a $2-per-gallon tax added?</p>
<div id="bd3dc2ee" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>gas_prices <span class="op">+</span> <span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>array([5.047, 5.043, 5.109, 5.103, 5.082, 5.128, 5.148, 5.125, 5.078,
       5.069, 5.058, 5.115, 5.162, 5.243, 5.168, 5.141, 5.133, 5.147,
       5.12 , 5.173, 5.16 , 5.127, 5.108, 5.139, 5.213, 5.164, 5.125,
       5.13 , 5.121, 5.123, 5.14 , 5.118, 5.125, 5.147, 5.177, 5.192,
       5.168, 5.173, 5.118, 5.124, 5.061, 5.019, 5.035, 5.019, 5.056,
       5.062, 5.061, 4.985, 4.94 , 4.895, 4.841, 4.811])</code></pre>
</div>
</div>
<p>When one value in an operation is a single number and the other is an array, NumPy applies the operation between that number and <em>every</em> element of the array. This pattern is called <strong>broadcasting</strong>, and it is what makes all the vectorized arithmetic in this chapter work.</p>
<p>Arithmetic between <em>two arrays</em> of the same length also works element by element: the first elements combine, then the second elements, and so on. This solves the “add two lists of numbers together” problem from the start of the chapter in one line:</p>
<div id="61ca9256" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Each element of the first array pairs with the matching element of the second</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>np.array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]) <span class="op">+</span> np.array([<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>array([11, 22, 33])</code></pre>
</div>
</div>
</section>
<section id="summarizing-an-array-with-a-single-number" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="summarizing-an-array-with-a-single-number"><span class="header-section-number">4.5.2</span> Summarizing an array with a single number</h3>
<p>Each summary function reduces the entire array down to one value in a single call. What was the average price of gas over the year?</p>
<div id="d02bb059" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two measures of the "typical" price</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>[np.mean(gas_prices), np.median(gas_prices)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>[np.float64(3.0974807692307698), np.float64(3.122)]</code></pre>
</div>
</div>
<p>Both values are about $3.10, so a typical week’s price was a little over three dollars a gallon. What were the cheapest and most expensive weeks?</p>
<div id="7f7b7eb9" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>[np.<span class="bu">min</span>(gas_prices), np.<span class="bu">max</span>(gas_prices)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>[np.float64(2.811), np.float64(3.243)]</code></pre>
</div>
</div>
<p>Prices ranged from a low of about $2.81 to a high of about $3.24. A natural follow-up question is <em>when</em> those weeks occurred. The functions <code>np.argmin()</code> and <code>np.argmax()</code> give us the <strong>position</strong> of the smallest and largest values, which we can then use to look up the matching date:</p>
<div id="36f1bf93" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The date of the most expensive week</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>gas_dates[np.argmax(gas_prices)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>np.datetime64('2025-04-07T00:00:00.000000')</code></pre>
</div>
</div>
<p>Gas was at its most expensive in early April. We can also add up all the values with <code>np.sum()</code>. If you bought exactly one gallon of gas every week of the year, the total spent would be:</p>
<div id="09b984f0" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(gas_prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<pre><code>np.float64(161.06900000000002)</code></pre>
</div>
</div>
<p>NumPy also has functions for measuring <strong>spread</strong>: how much the values vary around the average. <code>np.std()</code> gives the standard deviation, the typical distance of each value from the mean. A small standard deviation means prices were stable; a large one means they fluctuated:</p>
<div id="ec4e6650" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>np.std(gas_prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>np.float64(0.08359851176091028)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you cross-check this against the previous chapter’s tools, you will get a slightly different number: <code>np.std()</code> divides by <span class="math inline">\(n\)</span> while <code>statistics.stdev()</code> divides by <span class="math inline">\(n - 1\)</span>. For 52 values the difference is small, and which version to use rarely matters at this stage.</p>
</div>
</div>
<p>Percentiles tell you the value below which a given share of the data falls: 25% of the weeks had prices below the 25th percentile, and 75% of the weeks had prices below the 75th percentile. (The median you met in the previous chapter is the 50th percentile.) <code>np.percentile()</code> takes the array and the percentile you want:</p>
<div id="6f4bd75a" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 25th and 75th percentile of weekly gas prices</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>[np.percentile(gas_prices, <span class="dv">25</span>), np.percentile(gas_prices, <span class="dv">75</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>[np.float64(3.061), np.float64(3.147)]</code></pre>
</div>
</div>
<p>The gap between those two values is the <strong>interquartile range (IQR)</strong>: the spread of the middle 50% of the data. Because it ignores the top and bottom quarters, it is less affected by unusually high or low weeks than the full range:</p>
<div id="0452f758" class="cell" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Interquartile range: the spread of the middle 50% of the data</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>np.percentile(gas_prices, <span class="dv">75</span>) <span class="op">-</span> np.percentile(gas_prices, <span class="dv">25</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>np.float64(0.08599999999999985)</code></pre>
</div>
</div>
<div id="exercise-array_computations-spread" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>np.std()</code> to find the standard deviation of the gas prices. Then compute the IQR using <code>np.percentile()</code>. Which is larger?</p>
</div>
</div>
<div id="solution-array_computations-spread" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="be685103" class="cell" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>std <span class="op">=</span> np.std(gas_prices)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> np.percentile(gas_prices, <span class="dv">75</span>) <span class="op">-</span> np.percentile(gas_prices, <span class="dv">25</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>[std, iqr]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>[np.float64(0.08359851176091028), np.float64(0.08599999999999985)]</code></pre>
</div>
</div>
<p>For this data the IQR is slightly larger than the standard deviation. The two are not directly comparable, though, because they measure spread in different ways: the IQR is the <em>width of the interval</em> covering the middle half of the data, while the standard deviation is a typical <em>distance of one value</em> from the mean. Each is useful for comparing the same measure across datasets, not for comparing against the other.</p>
</div>
</div>
</div>
</section>
<section id="working-across-a-sequence" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="working-across-a-sequence"><span class="header-section-number">4.5.3</span> Working across a sequence</h3>
<p>Because our prices are in weekly order, some NumPy functions are especially useful. <code>np.cumsum()</code> gives the <strong>cumulative sum</strong>: the running total spent after each week.</p>
<div id="4f554432" class="cell" data-execution_count="36">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Running total if you bought one gallon each week</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>np.cumsum(gas_prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>array([  3.047,   6.09 ,   9.199,  12.302,  15.384,  18.512,  21.66 ,
        24.785,  27.863,  30.932,  33.99 ,  37.105,  40.267,  43.51 ,
        46.678,  49.819,  52.952,  56.099,  59.219,  62.392,  65.552,
        68.679,  71.787,  74.926,  78.139,  81.303,  84.428,  87.558,
        90.679,  93.802,  96.942, 100.06 , 103.185, 106.332, 109.509,
       112.701, 115.869, 119.042, 122.16 , 125.284, 128.345, 131.364,
       134.399, 137.418, 140.474, 143.536, 146.597, 149.582, 152.522,
       155.417, 158.258, 161.069])</code></pre>
</div>
</div>
<p>A small example shows the mechanics more clearly than 52 weeks of data. Each value in the running total is the sum of the corresponding array value and every value before it, so the running total carries forward from one box to the next:</p>
<div id="67e1e375" class="cell" data-execution_count="37">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-38-output-1.png" width="577" height="291" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Even more useful for a time series is <code>np.diff()</code>, which gives the difference between each value and the one before it: how much the price <em>changed</em> from one week to the next.</p>
<div id="36add926" class="cell" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Week-to-week changes in the price of gas</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>weekly_changes <span class="op">=</span> np.diff(gas_prices)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>weekly_changes</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>array([-0.004,  0.066, -0.006, -0.021,  0.046,  0.02 , -0.023, -0.047,
       -0.009, -0.011,  0.057,  0.047,  0.081, -0.075, -0.027, -0.008,
        0.014, -0.027,  0.053, -0.013, -0.033, -0.019,  0.031,  0.074,
       -0.049, -0.039,  0.005, -0.009,  0.002,  0.017, -0.022,  0.007,
        0.022,  0.03 ,  0.015, -0.024,  0.005, -0.055,  0.006, -0.063,
       -0.042,  0.016, -0.016,  0.037,  0.006, -0.001, -0.076, -0.045,
       -0.045, -0.054, -0.03 ])</code></pre>
</div>
</div>
<p><code>np.diff()</code> works on the same example: each output value is the difference between two adjacent inputs, so there is one fewer output than input:</p>
<div id="22bd28b4" class="cell" data-execution_count="39">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-40-output-1.png" width="577" height="291" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The result has 51 values rather than 52, because 52 weeks produce only 51 gaps. Now we can answer an interesting question: what was the single largest weekly change in price? Since a change can be a drop (negative) or a rise (positive), we use <code>np.abs()</code> to look at the <em>size</em> of each change regardless of direction, and <code>np.max()</code> to find the biggest:</p>
<div id="5aecda64" class="cell" data-execution_count="40">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The size of the largest single-week change</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">max</span>(np.<span class="bu">abs</span>(weekly_changes))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>np.float64(0.08099999999999996)</code></pre>
</div>
</div>
<p>The biggest swing in any week was about 8 cents. Combining this with <code>np.argmax()</code> and our dates, we can find exactly which week saw that change. There is one subtlety: because <code>weekly_changes</code> describes the gaps <em>between</em> weeks, its positions are shifted by one from the weeks themselves. The first change (position 0) is the jump from week 0 to week 1, so it belongs to week 1; the change at any position therefore corresponds to the date one position later. That’s why we add 1 before looking up the date:</p>
<div id="82704aad" class="cell" data-execution_count="41">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The week in which the largest change occurred.</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We add 1 because each change belongs to the *later* of the two weeks it spans.</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>gas_dates[np.argmax(np.<span class="bu">abs</span>(weekly_changes)) <span class="op">+</span> <span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>np.datetime64('2025-04-07T00:00:00.000000')</code></pre>
</div>
</div>
<p>The line plot at the start of the chapter showed <em>when</em> prices moved. A histogram of <code>weekly_changes</code> shows <em>how much</em> prices typically moved from one week to the next:</p>
<div id="4d947e44" class="cell" data-execution_count="42">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>plt.hist(weekly_changes, bins<span class="op">=</span><span class="dv">15</span>, edgecolor<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Week-to-week price change ($)"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Number of weeks"</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Distribution of weekly gas price changes, 2025"</span>)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-43-output-1.png" width="577" height="451" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The changes cluster around zero: in most weeks the price moved less than five cents in either direction, and no week moved more than about eight cents.</p>
<div id="exercise-array_computations-changes" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>np.diff()</code> and <code>np.min()</code> to find the <em>largest single-week drop</em> in the price of gas (the most negative weekly change). Then find the date of the week in which it occurred.</p>
</div>
</div>
<div id="solution-array_computations-changes" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="7067e2ae" class="cell" data-execution_count="43">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>weekly_changes <span class="op">=</span> np.diff(gas_prices)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The largest drop is the most negative change, so we use np.min</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>largest_drop <span class="op">=</span> np.<span class="bu">min</span>(weekly_changes)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="co"># np.argmin gives the position of that drop; add 1 to get the later week</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>drop_date <span class="op">=</span> gas_dates[np.argmin(weekly_changes) <span class="op">+</span> <span class="dv">1</span>]</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>[largest_drop, drop_date]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>[np.float64(-0.07600000000000007), np.datetime64('2025-12-01T00:00:00.000000')]</code></pre>
</div>
</div>
<p>The largest single-week drop was about 8 cents, in the week ending in early December.</p>
</div>
</div>
</div>
</section>
</section>
<section id="boolean-arrays-and-boolean-indexing" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="boolean-arrays-and-boolean-indexing"><span class="header-section-number">4.6</span> Boolean arrays and Boolean indexing</h2>
<p>So far our questions have been about all the prices together. Often, though, we want to focus on values that meet some condition, such as the weeks where gas was cheap. NumPy handles this with <strong>Boolean arrays</strong>.</p>
<p>A Boolean array is just an array of <code>True</code>/<code>False</code> values. We can build one by hand, the same way we build any other array:</p>
<div id="941c774a" class="cell" data-execution_count="44">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>np.array([<span class="va">True</span>, <span class="va">False</span>, <span class="va">True</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>array([ True, False,  True])</code></pre>
</div>
</div>
<p>More often, though, we create one by writing a <strong>comparison</strong> against an array. NumPy compares every element and returns an array of the results:</p>
<div id="6a4a951a" class="cell" data-execution_count="45">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Was the price below $3.00 in each week?</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>gas_prices <span class="op">&lt;</span> <span class="fl">3.00</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True])</code></pre>
</div>
</div>
<p>Because Python treats <code>True</code> as 1 and <code>False</code> as 0, we can <em>count</em> how many weeks met our condition by summing the Boolean array, and find the <em>proportion</em> of weeks by taking its mean:</p>
<div id="6fb6be38" class="cell" data-execution_count="46">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many weeks was gas below $3.00?</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(gas_prices <span class="op">&lt;</span> <span class="fl">3.00</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>np.int64(5)</code></pre>
</div>
</div>
<div id="a20352d6" class="cell" data-execution_count="47">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What fraction of weeks was gas below $3.00?</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>np.mean(gas_prices <span class="op">&lt;</span> <span class="fl">3.00</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<pre><code>np.float64(0.09615384615384616)</code></pre>
</div>
</div>
<p>Gas dipped below $3.00 in only 5 of the 52 weeks, or about 10% of the year. We can build more specific conditions by combining comparisons with <code>&amp;</code> (“and”) and <code>|</code> (“or”). Each comparison must be wrapped in parentheses:</p>
<div id="a9a27d85" class="cell" data-execution_count="48">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many weeks was the price between $3.00 and $3.20?</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>((gas_prices <span class="op">&gt;</span> <span class="fl">3.00</span>) <span class="op">&amp;</span> (gas_prices <span class="op">&lt;</span> <span class="fl">3.20</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<pre><code>np.int64(45)</code></pre>
</div>
</div>
<section id="boolean-indexing" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="boolean-indexing"><span class="header-section-number">4.6.1</span> Boolean indexing</h3>
<p>Beyond counting, we can use a Boolean array to <em>pull out</em> the values that meet a condition. This is called <strong>Boolean indexing</strong> or <strong>masking</strong>. To see how it works, start with a mask built by hand. Indexing an array with a Boolean array of the same length keeps the values where the mask is <code>True</code> and drops the values where it is <code>False</code>:</p>
<div id="8fda2e94" class="cell" data-execution_count="49">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>small_prices <span class="op">=</span> np.array([<span class="fl">3.05</span>, <span class="fl">3.04</span>, <span class="fl">3.11</span>])</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>mask <span class="op">=</span> np.array([<span class="va">True</span>, <span class="va">False</span>, <span class="va">True</span>])</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>small_prices[mask]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<pre><code>array([3.05, 3.11])</code></pre>
</div>
</div>
<div id="7e497181" class="cell" data-execution_count="50">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-51-output-1.png" width="577" height="305" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In practice we rarely type a mask by hand. Instead we produce one with a comparison, then index with it in a single expression:</p>
<div id="144d7940" class="cell" data-execution_count="51">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The actual prices for the weeks when gas was below $3.00</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>gas_prices[gas_prices <span class="op">&lt;</span> <span class="fl">3.00</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>array([2.985, 2.94 , 2.895, 2.841, 2.811])</code></pre>
</div>
</div>
<p>The full value of masking appears when you then summarize the selected values. For example, <em>among the weeks when gas was below $3.00</em>, what was the average price?</p>
<div id="dc1a160b" class="cell" data-execution_count="52">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>np.mean(gas_prices[gas_prices <span class="op">&lt;</span> <span class="fl">3.00</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="52">
<pre><code>np.float64(2.8944)</code></pre>
</div>
</div>
<p>Masking also lets us fulfill a promise from the previous chapter: finding a dataset’s <strong>outliers</strong>. Recall the rule of thumb that flags any value more than 1.5 IQRs below the 25th percentile or above the 75th percentile. With <code>np.percentile()</code> and a compound condition, this takes only a few lines:</p>
<div id="3e2f2769" class="cell" data-execution_count="53">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>q1 <span class="op">=</span> np.percentile(gas_prices, <span class="dv">25</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>q3 <span class="op">=</span> np.percentile(gas_prices, <span class="dv">75</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> q3 <span class="op">-</span> q1</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>lower_fence <span class="op">=</span> q1 <span class="op">-</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>upper_fence <span class="op">=</span> q3 <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> iqr</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The prices that fall outside the fences</span></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>gas_prices[(gas_prices <span class="op">&lt;</span> lower_fence) <span class="op">|</span> (gas_prices <span class="op">&gt;</span> upper_fence)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<pre><code>array([2.895, 2.841, 2.811])</code></pre>
</div>
</div>
<p>The three outliers are the unusually cheap weeks at the very end of December, the same low tail we saw in the line plot.</p>
</section>
<section id="the-same-idea-on-other-data" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="the-same-idea-on-other-data"><span class="header-section-number">4.6.2</span> The same idea on other data</h3>
<p>The Bechdel Test data from the previous chapter gives a different example of the same idea. Recall that each movie either passes (<code>"PASS"</code>) or fails (<code>"FAIL"</code>) the test. The cell below loads the movies’ pass/fail status and international gross earnings into two arrays, again using the <code>pandas</code> loading code you can treat as a black box for now:</p>
<div id="45cc397a" class="cell" data-execution_count="54">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Bechdel data and pull two columns out as arrays</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>movies <span class="op">=</span> pd.read_csv(<span class="st">"https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bechdel/movies.csv"</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>movies <span class="op">=</span> movies[[<span class="st">"binary"</span>, <span class="st">"intgross_2013$"</span>]].dropna()</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>bechdel_status <span class="op">=</span> movies[<span class="st">"binary"</span>].values</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>intl_gross <span class="op">=</span> movies[<span class="st">"intgross_2013$"</span>].values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Using exactly the masking technique we just learned, we can compare the average earnings of movies that passed the test against those that failed:</p>
<div id="1606f948" class="cell" data-execution_count="55">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average international gross for movies that PASS vs. FAIL the Bechdel Test</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>[np.mean(intl_gross[bechdel_status <span class="op">==</span> <span class="st">"PASS"</span>]),</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a> np.mean(intl_gross[bechdel_status <span class="op">==</span> <span class="st">"FAIL"</span>])]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="55">
<pre><code>[np.float64(167359970.8358396), np.float64(222529817.73807105)]</code></pre>
</div>
</div>
<p>Movies that <em>failed</em> the Bechdel Test earned more on average than those that passed, the pattern FiveThirtyEight highlighted in its original analysis. The masking syntax is identical to the gas-price examples above. (Note that <code>bechdel_status</code> is an array of strings, like the mixed-type example earlier in the chapter, and comparisons work on it the same way they work on numbers.)</p>
<div id="exercise-array_computations-mask" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>gas_prices</code> array, count how many weeks the price was <em>above</em> the average price for the year. (Hint: you can use <code>np.mean(gas_prices)</code> directly inside a comparison.)</p>
</div>
</div>
<div id="solution-array_computations-mask" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="716e7b67" class="cell" data-execution_count="56">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(gas_prices <span class="op">&gt;</span> np.mean(gas_prices))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="56">
<pre><code>np.int64(34)</code></pre>
</div>
</div>
<p>The price was above the yearly average in 34 of the 52 weeks. (More than half the weeks can sit above the mean because the unusually cheap weeks at the end of the year pull the mean down, below the median.)</p>
</div>
</div>
</div>
</section>
</section>
<section id="higher-dimensional-arrays-and-image-processing" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="higher-dimensional-arrays-and-image-processing"><span class="header-section-number">4.7</span> Higher-dimensional arrays and image processing</h2>
<p>Every array we’ve used so far has been one-dimensional: a single row of numbers. But arrays can have more than one dimension. A two-dimensional array is just a grid of numbers, with rows and columns like a spreadsheet.</p>
<section id="creating-and-indexing-matrices" class="level3" data-number="4.7.1">
<h3 data-number="4.7.1" class="anchored" data-anchor-id="creating-and-indexing-matrices"><span class="header-section-number">4.7.1</span> Creating and indexing matrices</h3>
<p>A <strong>matrix</strong> is a 2D array, and the most direct way to build one is to pass <code>np.array()</code> a list of lists, with each inner list becoming one row:</p>
<div id="a2e5be1f" class="cell" data-execution_count="57">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>matrix <span class="op">=</span> np.array([</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>],</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>],</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>matrix</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="57">
<pre><code>array([[1, 2, 3],
       [4, 5, 6]])</code></pre>
</div>
</div>
<p>The <code>.shape</code> confirms the structure: 2 rows and 3 columns.</p>
<div id="f29ed86e" class="cell" data-execution_count="58">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>matrix.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="58">
<pre><code>(2, 3)</code></pre>
</div>
</div>
<p>Indexing a 2D array takes two positions separated by a comma: a row, then a column. <code>matrix[0, 1]</code> is the value in row 0, column 1:</p>
<div id="7d037a76" class="cell" data-execution_count="59">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>matrix[<span class="dv">0</span>, <span class="dv">1</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="59">
<pre><code>np.int64(2)</code></pre>
</div>
</div>
<p>A <code>:</code> in either position means “every value along that axis.” <code>matrix[1, :]</code> pulls out all of row 1, and <code>matrix[:, 2]</code> pulls out all of column 2:</p>
<div id="4c21be2c" class="cell" data-execution_count="60">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>[matrix[<span class="dv">1</span>, :], matrix[:, <span class="dv">2</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="60">
<pre><code>[array([4, 5, 6]), array([3, 6])]</code></pre>
</div>
</div>
<p>Slicing combines with indexing the same way: <code>matrix[0:2, 1:3]</code> keeps rows 0 and 1, and within those rows, columns 1 and 2:</p>
<div id="e14c56df" class="cell" data-execution_count="61">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>matrix[<span class="dv">0</span>:<span class="dv">2</span>, <span class="dv">1</span>:<span class="dv">3</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="61">
<pre><code>array([[2, 3],
       [5, 6]])</code></pre>
</div>
</div>
<p>The <code>axis</code> argument in NumPy functions specifies which dimension to operate along. On a 2D array, <code>axis=0</code> operates <em>down the rows</em>, producing one result per column, and <code>axis=1</code> operates <em>across the columns</em>, producing one result per row:</p>
<div id="5602270f" class="cell" data-execution_count="62">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum down the rows (axis=0): one total per column</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(matrix, axis<span class="op">=</span><span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="62">
<pre><code>array([5, 7, 9])</code></pre>
</div>
</div>
<div id="1583650e" class="cell" data-execution_count="63">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum across the columns (axis=1): one total per row</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(matrix, axis<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="63">
<pre><code>array([ 6, 15])</code></pre>
</div>
</div>
<p>The picture below shows the direction each version sums along, and the 1D array each one produces:</p>
<div id="fbc4e744" class="cell" data-execution_count="64">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-65-output-1.png" width="854" height="328" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We will use this same idea with <code>axis=2</code> when working with 3D color images later in this section.</p>
<div id="exercise-array_computations-matrix" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Create the matrix <code>[[1, 2, 3], [4, 5, 6], [7, 8, 9]]</code> using <code>np.array()</code>. Then use indexing to pull out the value 7, and slicing to pull out the entire bottom row.</p>
</div>
</div>
<div id="solution-array_computations-matrix" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="b1636ffe" class="cell" data-execution_count="65">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>small_matrix <span class="op">=</span> np.array([</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>],</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>],</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>],</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>[small_matrix[<span class="dv">2</span>, <span class="dv">0</span>], small_matrix[<span class="dv">2</span>, :]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="65">
<pre><code>[np.int64(7), array([7, 8, 9])]</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="grayscale-images-are-2d-arrays" class="level3" data-number="4.7.2">
<h3 data-number="4.7.2" class="anchored" data-anchor-id="grayscale-images-are-2d-arrays"><span class="header-section-number">4.7.2</span> Grayscale images are 2D arrays</h3>
<p>For a large grid, typing out every value as a list of lists is impractical, so we can ask NumPy to build the array for us. Here we start with a 100×100 grid of zeros using <code>np.zeros()</code>, then use slicing to set a square block of values in the middle to 1. Note that the <code>[100, 100]</code> we pass to <code>np.zeros()</code> is not a list of <em>values</em> (the way <code>np.array([3.05, 3.04])</code> was). It describes the <em>shape</em> we want: 100 rows and 100 columns. NumPy functions that accept a shape always expect it as a single list or tuple, not as separate arguments.</p>
<div id="82ea88e4" class="cell" data-execution_count="66">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A 100x100 grid of zeros (100 rows, 100 columns)</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.zeros([<span class="dv">100</span>, <span class="dv">100</span>])</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a square block of the grid to 1 using slicing on both dimensions</span></span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>grid[<span class="dv">30</span>:<span class="dv">70</span>, <span class="dv">30</span>:<span class="dv">70</span>] <span class="op">=</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Why make a grid of numbers? Because <strong>a grayscale image is exactly that</strong>: a 2D array where each number is the brightness of a pixel. If we display our grid as an image, the 1s show up as a white square on a black background:</p>
<div id="eedf47b7" class="cell" data-execution_count="67">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>plt.imshow(grid, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-68-output-1.png" width="415" height="415" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The picture below makes the connection precise: every position in the array has a row index (<strong>axis 0</strong>) and a column index (<strong>axis 1</strong>), and the <em>value</em> stored at that position controls how dark or light the pixel is. Stored photos typically use whole numbers from 0 (black) to 255 (white). (Our square example used 0 and 1 instead; by default Matplotlib stretches an array’s smallest value to black and its largest to white, which is why the 1s displayed as pure white.)</p>
<div id="43cd507d" class="cell" data-execution_count="68">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-69-output-1.png" width="855" height="357" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As a concrete example, consider the cameraman: a standard grayscale test image distributed with the <code>imageio</code> package and used in image-processing research for decades. Unlike most digital photos, it was stored from the start as a single 2D layer of brightness values with no color information:</p>
<div id="56f3c72e" class="cell" data-execution_count="69">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> imageio.v3 <span class="im">import</span> imread  <span class="co"># imread loads an image file into a NumPy array</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The "imageio:" prefix refers to a sample image bundled with the imageio</span></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co"># package, not a file on your computer</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>cameraman <span class="op">=</span> imread(<span class="st">"imageio:camera.png"</span>)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>plt.imshow(cameraman, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Imageio: 'camera.png' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/images/camera.png (136 kB)
Downloading: 8192/139512 bytes (5.9%)139512/139512 bytes (100.0%)
  Done
File saved as /home/runner/.imageio/images/camera.png.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-70-output-2.png" width="428" height="416" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Confirm that it really is a 2D array of numbers by checking its shape and data type:</p>
<div id="46be076f" class="cell" data-execution_count="70">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>[cameraman.shape, cameraman.dtype]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<pre><code>[(512, 512), dtype('uint8')]</code></pre>
</div>
</div>
<p>The shape <code>(512, 512)</code> tells us the photo is 512 pixels tall and 512 pixels wide, with a single brightness value at each position, just like the small example above. The data type <code>uint8</code> is an unsigned 8-bit integer: <code>u</code> means no negative values, and 8 bits gives exactly 256 possible values, from 0 to 255. Here 0 is black and 255 is white.</p>
</section>
<section id="color-images-are-3d-arrays" class="level3" data-number="4.7.3">
<h3 data-number="4.7.3" class="anchored" data-anchor-id="color-images-are-3d-arrays"><span class="header-section-number">4.7.3</span> Color images are 3D arrays</h3>
<p>Color photographs add a third dimension. Here we load a photo of bell peppers:</p>
<div id="ace297fc" class="cell" data-execution_count="71">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the image into a NumPy array (same imread as above; the file is stored locally)</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>peppers <span class="op">=</span> imread(<span class="st">"images/peppers.jpg"</span>)</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>plt.imshow(peppers)</span>
<span id="cb123-5"><a href="#cb123-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-72-output-1.png" width="575" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="552c7c18" class="cell" data-execution_count="72">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb124"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>[peppers.shape, peppers.dtype]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="72">
<pre><code>[(648, 960, 3), dtype('uint8')]</code></pre>
</div>
</div>
<p>The shape <code>(648, 960, 3)</code> says the image is 648 pixels tall and 960 pixels wide, with 3 values at each pixel position, one per color channel. Each channel holds the intensity of one color (red, green, or blue) at that pixel, using the same <code>uint8</code> range of 0 to 255. The diagram below shows how those three layers are organized; the outlined cell marks a single pixel, whose color is stored as three values at the same (row, column) position, one on each layer.</p>
<div id="b7f62476" class="cell" data-execution_count="73">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-74-output-1.png" width="503" height="509" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Combining different amounts of red, green, and blue <em>light</em> is how each pixel’s color is produced, an idea called <strong>additive color</strong>. Mixing any two of the three at full intensity produces yellow, magenta, or cyan; mixing all three produces white:</p>
<div id="e2a3241d" class="cell" data-execution_count="74">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-75-output-1.png" width="546" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Averaging the red, green, and blue values at each pixel collapses them to a single brightness value, in the same format as the grayscale photo earlier. Passing <code>axis=2</code> to <code>np.mean()</code> tells NumPy to average along the channel dimension: for each pixel position (row, column), it reduces the three channel values to one number, leaving an array of shape (height, width):</p>
<div id="cdc1a08c" class="cell" data-execution_count="75">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the red, green, and blue values at each pixel</span></span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>gray_peppers <span class="op">=</span> np.mean(peppers, axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>plt.imshow(gray_peppers, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-76-output-1.png" width="575" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="manipulating-an-image-is-just-array-computation" class="level3" data-number="4.7.4">
<h3 data-number="4.7.4" class="anchored" data-anchor-id="manipulating-an-image-is-just-array-computation"><span class="header-section-number">4.7.4</span> Manipulating an image is just array computation</h3>
<p>Because the image is an array, every NumPy tool from this chapter applies to it. Using slicing, we can pull out a single color channel (here, the red channel) and display it on its own. The effect is visible across the peppers: the red one appears nearly white (high red-channel values), while the green one appears dark (low red-channel values). The yellow pepper also appears bright, and the additive-color figure explains why: yellow is red plus green light, so its red channel is high too:</p>
<div id="d4316209" class="cell" data-execution_count="76">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep all rows and columns, but only the first (red) channel</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>red_channel <span class="op">=</span> peppers[:, :, <span class="dv">0</span>]</span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>plt.imshow(red_channel, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-77-output-1.png" width="575" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Boolean-array idea works on images too. Comparing the grayscale image to a threshold produces a Boolean array marking the brightest pixels, which we can display to highlight the lightest regions of the photo:</p>
<div id="ebbd70e3" class="cell" data-execution_count="77">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb128"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A Boolean array that is True for bright pixels</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>bright_pixels <span class="op">=</span> gray_peppers <span class="op">&gt;</span> <span class="dv">150</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>plt.imshow(bright_pixels, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-78-output-1.png" width="575" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The white regions are the pixels where the condition was <code>True</code>: here, the bright sky in the background and the yellow pepper.</p>
<p><strong>Images are just arrays.</strong> Slicing, arithmetic, <code>np.mean()</code> with an <code>axis</code> argument, and Boolean masks all work on image arrays the same way they work on any NumPy array.</p>
<div id="exercise-array_computations-image" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using the <code>gray_peppers</code> array from above, use Boolean indexing to count how many of its pixels are <em>darker</em> than a brightness of 50.</p>
</div>
</div>
<div id="solution-array_computations-image" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="ef8e6ef7" class="cell" data-execution_count="78">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the pixels whose brightness is below 50</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">sum</span>(gray_peppers <span class="op">&lt;</span> <span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="78">
<pre><code>np.int64(80398)</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="summary" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.8</span> Summary</h2>
<p>In this chapter we introduced NumPy arrays, the standard container for numerical data in Python. The key ideas were:</p>
<ul>
<li><strong>Arrays vs.&nbsp;lists.</strong> Arrays hold values of a single type and support <em>vectorized</em> operations, letting us transform every element at once instead of writing loops. This makes code shorter to write and faster to run.</li>
<li><strong>Creating and inspecting arrays.</strong> We build arrays with <code>np.array()</code>, <code>np.arange()</code>, and <code>np.linspace()</code>, and inspect them with attributes like <code>.shape</code>, <code>.dtype</code>, <code>.size</code>, and <code>.ndim</code>.</li>
<li><strong>Summarizing and transforming.</strong> Functions such as <code>np.mean()</code>, <code>np.median()</code>, <code>np.min()</code>, <code>np.max()</code>, <code>np.sum()</code>, <code>np.std()</code>, and <code>np.percentile()</code> reduce an array to a single number, while <code>np.diff()</code> and <code>np.cumsum()</code> are especially useful for sequences like time series.</li>
<li><strong>Boolean arrays.</strong> Comparisons produce arrays of <code>True</code>/<code>False</code> values that we can sum to count, average to find proportions, and use to index, pulling out and summarizing exactly the values that meet a condition.</li>
<li><strong>Higher-dimensional arrays.</strong> Two- and three-dimensional arrays represent grids and images, and every array tool we learned applies to them.</li>
</ul>
<p>Nearly every data science tool in Python builds on NumPy. In the chapters ahead we’ll use it to work with full data tables and to create richer visualizations.</p>
</section>
<section id="code-summary" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="code-summary"><span class="header-section-number">4.9</span> Code summary</h2>
<p>The functions and methods introduced in this chapter. NumPy is imported as <code>np</code>.</p>
<p><strong>Creating arrays</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>np.array([1, 2, 3])</code></td>
<td>Builds an array from a list</td>
</tr>
<tr class="even">
<td><code>np.arange(start, stop)</code></td>
<td>Whole numbers from <code>start</code> up to but not including <code>stop</code></td>
</tr>
<tr class="odd">
<td><code>np.linspace(start, stop, n)</code></td>
<td><code>n</code> evenly spaced values, including both endpoints</td>
</tr>
<tr class="even">
<td><code>np.zeros(shape)</code></td>
<td>An array of the given shape filled with zeros</td>
</tr>
<tr class="odd">
<td><code>arr.astype(float)</code></td>
<td>A copy of the array converted to another type</td>
</tr>
<tr class="even">
<td><code>arr.copy()</code></td>
<td>An independent copy, so changing one does not change the other</td>
</tr>
</tbody>
</table>
<p><strong>What an array is made of</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>arr.shape</code></td>
<td>The size along each dimension, as a tuple</td>
</tr>
<tr class="even">
<td><code>arr.size</code>, <code>arr.ndim</code></td>
<td>How many values in total, and how many dimensions</td>
</tr>
<tr class="odd">
<td><code>arr.dtype</code></td>
<td>The kind of value the array holds</td>
</tr>
</tbody>
</table>
<p><strong>Computing on every value at once</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>arr + 1</code>, <code>arr * 2</code></td>
<td>Arithmetic applied to every value, without a loop</td>
</tr>
<tr class="even">
<td><code>np.abs(arr)</code></td>
<td>The distance of each value from zero</td>
</tr>
<tr class="odd">
<td><code>np.cumsum(arr)</code></td>
<td>A running total, one value per position</td>
</tr>
<tr class="even">
<td><code>np.diff(arr)</code></td>
<td>The gap between each pair of neighbors, giving one fewer value</td>
</tr>
</tbody>
</table>
<p><strong>Summarizing an array</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>np.mean(arr)</code>, <code>np.median(arr)</code></td>
<td>The average and the middle value</td>
</tr>
<tr class="even">
<td><code>np.std(arr)</code></td>
<td>The standard deviation</td>
</tr>
<tr class="odd">
<td><code>np.sum(arr)</code></td>
<td>The total</td>
</tr>
<tr class="even">
<td><code>np.min(arr)</code>, <code>np.max(arr)</code></td>
<td>The smallest and largest value</td>
</tr>
<tr class="odd">
<td><code>np.argmin(arr)</code>, <code>np.argmax(arr)</code></td>
<td>The <em>position</em> of the smallest or largest value</td>
</tr>
<tr class="even">
<td><code>np.percentile(arr, p)</code></td>
<td>The value below which <code>p</code> percent of the data falls</td>
</tr>
</tbody>
</table>
<p><strong>Selecting values</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>arr[0]</code>, <code>arr[-1]</code></td>
<td>One value, by position, counting from zero</td>
</tr>
<tr class="even">
<td><code>arr[1:4]</code></td>
<td>A slice, from position 1 up to but not including 4</td>
</tr>
<tr class="odd">
<td><code>arr &gt; 3</code></td>
<td>An array of <code>True</code> and <code>False</code>, one per value</td>
</tr>
<tr class="even">
<td><code>arr[arr &gt; 3]</code></td>
<td>Keeps only the values where the condition is <code>True</code></td>
</tr>
<tr class="odd">
<td><code>(arr &gt; 1) &amp; (arr &lt; 4)</code></td>
<td>Combines conditions, with <code>&amp;</code> for and and <code>|</code> for or</td>
</tr>
<tr class="even">
<td><code>np.sum(mask)</code>, <code>np.mean(mask)</code></td>
<td>Counts how many are <code>True</code>, and what fraction are</td>
</tr>
</tbody>
</table>
<p><strong>Two- and three-dimensional arrays</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Code</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>matrix[row, col]</code></td>
<td>One value, by row and column</td>
</tr>
<tr class="even">
<td><code>matrix[0:2, 0:2]</code></td>
<td>A rectangular block of the array</td>
</tr>
<tr class="odd">
<td><code>np.sum(matrix, axis=0)</code></td>
<td>Summarizes down the columns; <code>axis=1</code> works across the rows</td>
</tr>
<tr class="even">
<td><code>imread("file.jpg")</code></td>
<td>Reads an image into an array of pixel values</td>
</tr>
<tr class="odd">
<td><code>plt.imshow(img)</code></td>
<td>Displays an array as a picture</td>
</tr>
</tbody>
</table>
</section>
<section id="exercises" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="exercises"><span class="header-section-number">4.10</span> Exercises</h2>
<div id="exercise-array_computations-cents" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Create a NumPy array of the gas prices expressed in <strong>cents</strong> rather than dollars (so $3.05 becomes 305 cents). Then find the average price in cents.</p>
</div>
</div>
<div id="solution-array_computations-cents" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="48728ec0" class="cell" data-execution_count="79">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>prices_in_cents <span class="op">=</span> gas_prices <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>[prices_in_cents, np.mean(prices_in_cents)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="79">
<pre><code>[array([304.7, 304.3, 310.9, 310.3, 308.2, 312.8, 314.8, 312.5, 307.8,
        306.9, 305.8, 311.5, 316.2, 324.3, 316.8, 314.1, 313.3, 314.7,
        312. , 317.3, 316. , 312.7, 310.8, 313.9, 321.3, 316.4, 312.5,
        313. , 312.1, 312.3, 314. , 311.8, 312.5, 314.7, 317.7, 319.2,
        316.8, 317.3, 311.8, 312.4, 306.1, 301.9, 303.5, 301.9, 305.6,
        306.2, 306.1, 298.5, 294. , 289.5, 284.1, 281.1]),
 np.float64(309.74807692307695)]</code></pre>
</div>
</div>
</div>
</div>
</div>
<div id="exercise-array_computations-range" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>range</strong> of a dataset is the difference between its largest and smallest values. Use <code>np.max()</code> and <code>np.min()</code> to compute the range of the gas prices for the year.</p>
</div>
</div>
<div id="solution-array_computations-range" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="1a0fb02d" class="cell" data-execution_count="80">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb133"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>np.<span class="bu">max</span>(gas_prices) <span class="op">-</span> np.<span class="bu">min</span>(gas_prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="80">
<pre><code>np.float64(0.43199999999999994)</code></pre>
</div>
</div>
<p>Gas prices varied by about 43 cents between the cheapest and most expensive weeks of the year.</p>
</div>
</div>
</div>
<div id="exercise-array_computations-firsthalf" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use slicing and <code>np.mean()</code> to compare the average gas price in the first half of the year (the first 26 weeks) to the average in the second half (the last 26 weeks). Did gas get cheaper or more expensive on average?</p>
</div>
</div>
<div id="solution-array_computations-firsthalf" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="b8e6c685" class="cell" data-execution_count="81">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>first_half_avg <span class="op">=</span> np.mean(gas_prices[<span class="dv">0</span>:<span class="dv">26</span>])</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>second_half_avg <span class="op">=</span> np.mean(gas_prices[<span class="dv">26</span>:<span class="dv">52</span>])</span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-4"><a href="#cb135-4" aria-hidden="true" tabindex="-1"></a>[first_half_avg, second_half_avg]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="81">
<pre><code>[np.float64(3.127038461538461), np.float64(3.0679230769230768)]</code></pre>
</div>
</div>
<p>Gas was more expensive in the first half of the year than in the second half, consistent with the downward drift we saw in the line plot.</p>
</div>
</div>
</div>
<div id="exercise-array_computations-boxplot" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this chapter we compared movies that passed and failed the Bechdel Test using only their <em>average</em> international gross. Averages can hide a lot. Use Boolean masking to create two arrays, <code>pass_gross</code> and <code>fail_gross</code>, holding the international gross of the passing and failing movies. Then display them as side-by-side box plots (which you met in the previous chapter) by passing a list of the two arrays to <code>plt.boxplot()</code>. Does the comparison look different from the comparison of means?</p>
</div>
</div>
<div id="solution-array_computations-boxplot" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="d6a55104" class="cell" data-execution_count="82">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>pass_gross <span class="op">=</span> intl_gross[bechdel_status <span class="op">==</span> <span class="st">"PASS"</span>]</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>fail_gross <span class="op">=</span> intl_gross[bechdel_status <span class="op">==</span> <span class="st">"FAIL"</span>]</span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a>plt.boxplot([pass_gross, fail_gross])</span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a>plt.xticks([<span class="dv">1</span>, <span class="dv">2</span>], [<span class="st">"PASS"</span>, <span class="st">"FAIL"</span>])</span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"International gross (2013 dollars)"</span>)</span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"International gross by Bechdel Test result"</span>)</span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-83-output-1.png" width="590" height="432" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The two distributions overlap heavily, and both are dominated by a small number of very high-grossing outlier movies. The difference between the groups looks much less dramatic here than the comparison of means suggested, a reminder that a single summary number can hide the shape of the data.</p>
</div>
</div>
</div>
<div id="exercise-array_computations-swap" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Create a version of the <code>peppers</code> image with the red and blue channels swapped, and display it. (Hint: make a copy first with <code>swapped = peppers.copy()</code> so you don’t change the original, then use slice assignment to set the copy’s red channel to the original’s blue channel and vice versa.)</p>
</div>
</div>
<div id="solution-array_computations-swap" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="92c502ad" class="cell" data-execution_count="83">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb138"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a>swapped <span class="op">=</span> peppers.copy()</span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the copy's red channel to the original's blue channel, and vice versa</span></span>
<span id="cb138-4"><a href="#cb138-4" aria-hidden="true" tabindex="-1"></a>swapped[:, :, <span class="dv">0</span>] <span class="op">=</span> peppers[:, :, <span class="dv">2</span>]</span>
<span id="cb138-5"><a href="#cb138-5" aria-hidden="true" tabindex="-1"></a>swapped[:, :, <span class="dv">2</span>] <span class="op">=</span> peppers[:, :, <span class="dv">0</span>]</span>
<span id="cb138-6"><a href="#cb138-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb138-7"><a href="#cb138-7" aria-hidden="true" tabindex="-1"></a>plt.imshow(swapped)</span>
<span id="cb138-8"><a href="#cb138-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="array_computations_files/figure-html/cell-84-output-1.png" width="575" height="398" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The red pepper now appears blue and the yellow pepper turns cyan (its red light became blue light, and cyan is green plus blue). The green pepper barely changes, since its color lives mostly in the untouched green channel.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./descriptive_stats_and_plots.html" class="pagination-link" aria-label="Descriptive statistics and plots">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive statistics and plots</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data_tables.html" class="pagination-link" aria-label="Data tables">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data tables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>