<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.11.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Introduction – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./python_basics.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d5b4e69c7e37b49c6591bcc5116dd748.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3d497cff885f6278d37568d0ef0763f8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./introduction.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./python_basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Python basics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_stats_and_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive statistics and plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./array_computations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Array computations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data tables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interactive_visualizations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Interactive visualizations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Maps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iteration_and_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Iteration and writing functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Introduction to statistical inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis_testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unsupervised_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Unsupervised learning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./web_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Web data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./where_next.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Where to go next</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-first-look-at-a-data-science-analysis" id="toc-a-first-look-at-a-data-science-analysis" class="nav-link active" data-scroll-target="#a-first-look-at-a-data-science-analysis"><span class="header-section-number">1.1</span> A first look at a data science analysis</a></li>
  <li><a href="#what-is-data-science" id="toc-what-is-data-science" class="nav-link" data-scroll-target="#what-is-data-science"><span class="header-section-number">1.2</span> What is data science?</a>
  <ul class="collapse">
  <li><a href="#data-science-and-statistics" id="toc-data-science-and-statistics" class="nav-link" data-scroll-target="#data-science-and-statistics"><span class="header-section-number">1.2.1</span> Data science and statistics</a></li>
  <li><a href="#what-data-cannot-do" id="toc-what-data-cannot-do" class="nav-link" data-scroll-target="#what-data-cannot-do"><span class="header-section-number">1.2.2</span> What data cannot do</a></li>
  <li><a href="#how-data-science-became-a-field" id="toc-how-data-science-became-a-field" class="nav-link" data-scroll-target="#how-data-science-became-a-field"><span class="header-section-number">1.2.3</span> How data science became a field</a></li>
  </ul></li>
  <li><a href="#what-a-data-science-project-looks-like" id="toc-what-a-data-science-project-looks-like" class="nav-link" data-scroll-target="#what-a-data-science-project-looks-like"><span class="header-section-number">1.3</span> What a data science project looks like</a></li>
  <li><a href="#writing-analyses-others-can-check" id="toc-writing-analyses-others-can-check" class="nav-link" data-scroll-target="#writing-analyses-others-can-check"><span class="header-section-number">1.4</span> Writing analyses others can check</a>
  <ul class="collapse">
  <li><a href="#jupyter-notebooks" id="toc-jupyter-notebooks" class="nav-link" data-scroll-target="#jupyter-notebooks"><span class="header-section-number">1.4.1</span> Jupyter notebooks</a></li>
  <li><a href="#the-order-cells-run-in" id="toc-the-order-cells-run-in" class="nav-link" data-scroll-target="#the-order-cells-run-in"><span class="header-section-number">1.4.2</span> The order cells run in</a></li>
  </ul></li>
  <li><a href="#building-on-the-work-of-others" id="toc-building-on-the-work-of-others" class="nav-link" data-scroll-target="#building-on-the-work-of-others"><span class="header-section-number">1.5</span> Building on the work of others</a>
  <ul class="collapse">
  <li><a href="#the-packages-we-will-use" id="toc-the-packages-we-will-use" class="nav-link" data-scroll-target="#the-packages-we-will-use"><span class="header-section-number">1.5.1</span> The packages we will use</a></li>
  <li><a href="#getting-set-up" id="toc-getting-set-up" class="nav-link" data-scroll-target="#getting-set-up"><span class="header-section-number">1.5.2</span> Getting set up</a></li>
  </ul></li>
  <li><a href="#how-to-use-this-book" id="toc-how-to-use-this-book" class="nav-link" data-scroll-target="#how-to-use-this-book"><span class="header-section-number">1.6</span> How to use this book</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">1.7</span> Summary</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">1.8</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-introduction" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Do you know how popular your name was when you were born? Most people have only a vague sense of it. They may recall that their name felt ordinary in their class, or that they were the only one who had it, or that they tend to meet the name mostly among people either much older or much younger than they are.</p>
<p>This vague sense can be replaced with a more precise quantitative answer. The U.S. Social Security Administration has kept a record of the first names on Social Security card applications going back to 1880, and it publishes the thousand most common names for each sex in each year. If your name was somewhat popular, then somewhere in that file is the year your name peaked, and whether it is currently increasing or decreasing in popularity.</p>
<p>This book is about turning questions like this into answers. The tools involved are a programming language, some statistical concepts, and ways of thiking about evidence. These are the skills we aim to develop over the course of this book.</p>
<section id="a-first-look-at-a-data-science-analysis" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="a-first-look-at-a-data-science-analysis"><span class="header-section-number">1.1</span> A first look at a data science analysis</h2>
<p>Before defining what the field of Data Science is, it is useful to see what a small analysis that is typical of a Data Science project. The code below loads the baby-name compiiled from the Social Security Administration records and plots the popularity of four female names over time.</p>
<p>You are not expected to understand this code. It is here so you know what you are working toward. Its pieces arrive over the next several chapters: <span class="quarto-unresolved-ref">?sec-descriptive-stats</span> teaches the plotting, <span class="quarto-unresolved-ref">?sec-data-tables</span> teaches how to load a file and pull out the rows for one name, and <a href="iteration_and_functions.html" class="quarto-xref"><span>Chapter 9</span></a> covers the <code>for</code> line that repeats the work for each name.</p>
<div id="922e2aa9" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># One row per name, per year, per sex: the 1,000 most common names each</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># year from 1880 to 2025</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> pd.read_csv(<span class="st">"https://raw.githubusercontent.com/emeyers/intro_datascience/main/data/babynames/baby_names.csv"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>names.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">percent</th>
<th data-quarto-table-cell-role="th">sex</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1880</td>
<td>John</td>
<td>0.081546</td>
<td>boy</td>
<td>9655</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1880</td>
<td>William</td>
<td>0.080507</td>
<td>boy</td>
<td>9532</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1880</td>
<td>James</td>
<td>0.050060</td>
<td>boy</td>
<td>5927</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1880</td>
<td>Charles</td>
<td>0.045169</td>
<td>boy</td>
<td>5348</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1880</td>
<td>George</td>
<td>0.043294</td>
<td>boy</td>
<td>5126</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Before computing anything, it is important to understand the data we are working with. Each row in the data records one name, in one year, for one sex. The <code>count</code> column gives the number of babies who received that name, and the <code>percent</code> column expresses the same quantity as a share of all babies of that sex born that year. That share is stored as a proportion rather than as a percentage, so the value <code>0.081546</code> in the first row means that 8.2% of boys born in 1880 were named John.</p>
<p>With the contents of the file established, we can plot how the popularity of individual names has changed over time:</p>
<div id="d16fb145" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>girls <span class="op">=</span> names[names[<span class="st">"sex"</span>] <span class="op">==</span> <span class="st">"girl"</span>]</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> [<span class="st">"Mary"</span>, <span class="st">"Linda"</span>, <span class="st">"Jennifer"</span>, <span class="st">"Emily"</span>]:</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    one_name <span class="op">=</span> girls[girls[<span class="st">"name"</span>] <span class="op">==</span> name]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    plt.plot(one_name[<span class="st">"year"</span>], one_name[<span class="st">"percent"</span>] <span class="op">*</span> <span class="dv">100</span>, label<span class="op">=</span>name)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of girls given the name"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-3-output-1.png" width="577" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Each of these four names dominated a different era. Mary was the most common girls’ name in the United States in 76 of the 82 years from 1880 to 1961, and in 1880 it was given to 7.2% of girls. Jennifer reached its peak in 1974, at 4.0%, and Emily reached its own in 1999, at 1.4%.</p>
<p>The trajectory of Linda is the most abrupt of the four. In 1946 the name was given to 3.3% of American girls, and in 1947 that figure jumped to 5.5%. Names rarely move that quickly, and 1947 happens to be the year in which Buddy Clark’s recording of a song called “Linda”, with Ray Noble’s orchestra, was a number one hit.</p>
<p>It is worth being precise about what that last sentence establishes and what it does not. The data establishes the timing of the increase. The song is an explanation brought to the data from outside it, by someone who already knew that popular music influences what parents name their children. The explanation is plausible, but a file of names and counts cannot confirm it. Distinguishing between what the data shows and what we have supplied ourselves is a skill this book returns to repeatedly.</p>
<p>A second pattern in the plot is easier to overlook: the peaks grow steadily shorter over time. In 1880 the most common girls’ name was given to 7.2% of girls, whereas in 2025 the most common name, Olivia, was given to only 0.8%. Parents did not stop having favorites, but the pool of names they choose from has grown enormously. This represents a genuine change in American naming practices, and it emerged from nothing more than a file of names and counts.</p>
<p>The analysis is worth noting for two reasons. It answered a question that intuition alone could not, and it revealed a pattern that nobody had set out to look for.</p>
</section>
<section id="what-is-data-science" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="what-is-data-science"><span class="header-section-number">1.2</span> What is data science?</h2>
<p><strong>Data science</strong> is the practice of using computation and statistical reasoning to answer questions with data. In practice it draws on three things: enough programming to load data and reshape it, enough statistics to know which conclusions the data supports, and enough knowledge of the subject to ask a question worth asking and to recognize a wrong answer when one appears.</p>
<p>The last of these three is the one most easily underrated. Nothing in the baby-names code knows what a name is or what it means for one to be fashionable. The code established that the name Linda rose sharply in 1947, but the connection to a popular song came from a person who already knew that music influences naming and who went looking for such an explanation. An analysis that ignores the subject matter it concerns tends to produce results that are technically correct and of little use to anyone.</p>
<section id="data-science-and-statistics" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="data-science-and-statistics"><span class="header-section-number">1.2.1</span> Data science and statistics</h3>
<p>Data science and statistics overlap heavily, and the difference between them is one of emphasis rather than of subject matter. Both are concerned with drawing conclusions from data. They tend to differ in where the data comes from, and in what counts as a good reason to trust a method.</p>
<div id="tbl-stats-vs-ds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stats-vs-ds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.1: Two emphases in the analysis of data
</figcaption>
<div aria-describedby="tbl-stats-vs-ds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Statistics</th>
<th>Data science</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Where the data comes from</td>
<td>Often collected deliberately, to answer a specific question</td>
<td>Often collected for some other purpose, and reused</td>
</tr>
<tr class="even">
<td>Typical size</td>
<td>Small enough to handle by hand or with a single command</td>
<td>Often large enough that retrieving it is part of the problem</td>
</tr>
<tr class="odd">
<td>Why a method is trusted</td>
<td>It has mathematical guarantees under stated assumptions</td>
<td>It performs well when tested against data it has not seen</td>
</tr>
<tr class="even">
<td>How much programming</td>
<td>Sometimes little</td>
<td>Usually substantial</td>
</tr>
<tr class="odd">
<td>What comes out</td>
<td>An estimate, an interval, a test result</td>
<td>Any of those, plus predictions, visualizations, and working systems</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A statistician’s instinct is to ask what model produced this data and what follows mathematically if that model is right. A data scientist’s instinct is to try several approaches and see which one predicts best on data held back for the purpose. In practice that means fitting the method on most of the rows, then checking its predictions against rows deliberately kept aside. One camp says the proof is in the math; the other says the proof is in the pudding. Both instincts are correct, and both fail in characteristic ways when used alone.</p>
<p>The boundary between the two is not a sharp one, and most practitioners move back and forth across it depending on the problem in front of them. The table above describes two habits of mind rather than two distinct kinds of person.</p>
</section>
<section id="what-data-cannot-do" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="what-data-cannot-do"><span class="header-section-number">1.2.2</span> What data cannot do</h3>
<p>Two cautions belong at the beginning of a book like this rather than at the end.</p>
<p>The first is that data is a record of the world that produced it, and that record includes the world’s mistakes. A model trained on past hiring decisions learns the decisions that were actually made, biases included, and applying such a model at scale can spread those biases far faster than any individual could.</p>
<p>The second is that a pattern in data is not, by itself, evidence of a cause. We encountered this a few pages ago, when the plot showed the name Linda rising sharply in 1947 and the song was offered as an explanation from outside the data. The fact that two things move together does not establish that one of them produces the other, and separating these two possibilities accounts for much of the work involved in interpreting a result honestly.</p>
<p>Both problems recur throughout this book, because both are ordinary features of working with data rather than rare special cases.</p>
</section>
<section id="how-data-science-became-a-field" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="how-data-science-became-a-field"><span class="header-section-number">1.2.3</span> How data science became a field</h3>
<p>The practice of analyzing data is very old, but the name given to it here is recent.</p>
<p>Most of the pieces were in place well before the label existed. John Tukey argued in 1962 that data analysis deserved to be treated as a subject in its own right, broader than the mathematics it grew out of <span class="citation" data-cites="tukey1962">(<a href="#ref-tukey1962" role="doc-biblioref"><strong>tukey1962?</strong></a>)</span>. In 2001 William Cleveland proposed “data science” for an expanded version of statistics that took computing seriously <span class="citation" data-cites="cleveland2001">(<a href="#ref-cleveland2001" role="doc-biblioref"><strong>cleveland2001?</strong></a>)</span>, and Leo Breiman described the field as split between two cultures, one building probability models and one building algorithms judged by how well they predict <span class="citation" data-cites="breiman2001">(<a href="#ref-breiman2001" role="doc-biblioref"><strong>breiman2001?</strong></a>)</span>. The tools followed: Matplotlib in 2003, NumPy in 2005, scikit-learn in 2007, pandas in 2009. You will use all four in this book.</p>
<p>What made the field visible outside of universities was a series of public episodes. Some of them demonstrated what analyzing data could accomplish, while others demonstrated the ways in which it goes wrong, and the second group proved to be just as instructive as the first.</p>
<p><strong>Moneyball (2002–2003).</strong> The Oakland Athletics, working with one of the smallest payrolls in baseball, used statistical analysis to find players the traditional scouting system undervalued, and put together a season that included a twenty-game winning streak. Michael Lewis’s book made the story famous <span class="citation" data-cites="lewis2003">(<a href="#ref-lewis2003" role="doc-biblioref"><strong>lewis2003?</strong></a>)</span>. Careful analysis of ordinary, publicly available numbers had beaten the judgment of experts in a domain those experts were certain they understood.</p>
<p><strong>The Netflix Prize (2006–2009).</strong> Netflix offered a million dollars to anyone who could improve its recommendations by 10%, and released a large dataset of ratings so that anyone could try. A combined team won in September 2009 with an improvement of just over 10%. Opening the problem to everyone beat what Netflix’s own engineers had managed. Netflix then never put the winning system into production: it was an ensemble, meaning many separate models averaged together, and it was expensive to run and hard to maintain. A winning score on a leaderboard is not the same thing as a useful system. The competition left one more mark. Researchers showed that individuals could be identified in the supposedly anonymous ratings data by matching it against their public reviews on another film site <span class="citation" data-cites="narayanan2008">(<a href="#ref-narayanan2008" role="doc-biblioref"><strong>narayanan2008?</strong></a>)</span>, and in 2010 Netflix cancelled the planned sequel competition.</p>
<p><strong>FiveThirtyEight and election forecasting (2008–2016).</strong> Nate Silver’s statistical models called 49 of 50 states in the 2008 presidential election and all 50 in 2012, at a time when television coverage ran on the intuition of experienced commentators. Data journalism became a public genre. Then 2016 turned into the more instructive case. FiveThirtyEight gave Donald Trump roughly a 29% chance of winning, higher than most other forecasters, several of whom put it below 2%. He won, and forecasting was widely described as having failed. Whether a 29% forecast of something that then happens is a failure is a real question with a real answer, and answering it requires understanding what a probability claims in the first place. <a href="statistical_inference.html" class="quarto-xref"><span>Chapter 10</span></a> takes it up.</p>
<p><strong>Google Flu Trends (2008–2013).</strong> Google found that the volume of flu-related searches tracked influenza rates, and built a system that estimated flu activity faster than the Centers for Disease Control could report it. It was held up as proof that with enough data, careful modeling mattered less than sheer scale. Over time, however, its estimates drifted away from reality. By 2013 it was estimating roughly double the actual rate of flu-related doctor visits, in part because the model had been fitted years earlier and never refitted while both the world and Google’s own search behavior changed underneath it <span class="citation" data-cites="lazer2014">(<a href="#ref-lazer2014" role="doc-biblioref"><strong>lazer2014?</strong></a>)</span>. The service was eventually shut down. It is the standard cautionary example: more data did not remove the need to ask where the data came from.</p>
<p><strong>Data science gets a job title (2012).</strong> A <em>Harvard Business Review</em> article by Thomas Davenport and D.J. Patil called the data scientist “the sexiest job of the 21st century” and put the role in front of every executive who read the magazine <span class="citation" data-cites="davenport2012">(<a href="#ref-davenport2012" role="doc-biblioref"><strong>davenport2012?</strong></a>)</span>. Kaggle, founded in 2010, had already made the work competitive and public. The label mattered practically: it created job postings, degree programs, and a shared name for work people had been doing under half a dozen others. Universities followed, launching data science degrees and renaming departments. Yale renamed its Department of Statistics to the Department of Statistics and Data Science in March 2017.</p>
<p><strong>Weapons of Math Destruction (2016).</strong> Cathy O’Neil’s book documented predictive models used in sentencing, hiring, lending, and school evaluation that encoded existing inequities and applied them at scale, with little recourse for the people affected <span class="citation" data-cites="oneil2016">(<a href="#ref-oneil2016" role="doc-biblioref"><strong>oneil2016?</strong></a>)</span>. The same year, ProPublica’s investigation of the COMPAS recidivism model found that Black defendants were roughly twice as likely as white defendants to be wrongly flagged as high risk. Together these accounts established that the potential harms of predictive modeling were not hypothetical.</p>
<div id="a95e0779" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-4-output-1.png" width="577" height="285" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The conclusion of this story is comparatively undramatic. The job title gradually stopped being exotic and settled into an ordinary role in most industries. The useful parts of the initial excitement outlasted the excitement itself, and attention to the potential harms became a standard part of the work rather than an afterthought. The most recent wave of attention has moved to large language models, which <a href="where_next.html" class="quarto-xref"><span>Chapter 17</span></a> takes up at the end of the book.</p>
<div id="exercise-introduction-news-story" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find a recent news article whose central claim rests on data. Write down three things:</p>
<ol type="1">
<li>The question the analysis was trying to answer.</li>
<li>Where the data came from, and who collected it.</li>
<li>One thing the data cannot tell you, even if the analysis is done perfectly.</li>
</ol>
</div>
</div>
<div id="solution-introduction-news-story" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There is no single correct answer here, but a good one is specific. As an example, consider an article reporting that a city’s new bike lanes were followed by a drop in cycling injuries.</p>
<ol type="1">
<li><strong>The question.</strong> Did adding bike lanes reduce injuries to cyclists?</li>
<li><strong>The data.</strong> Police accident reports, collected by the city for administrative purposes rather than for this analysis. Injuries that were never reported to police are not in the data at all.</li>
<li><strong>What it cannot tell you.</strong> Whether the bike lanes <em>caused</em> the drop. Injuries might have fallen because fewer people cycled that year, because the weather was worse, or because a different safety campaign ran at the same time. The data records what happened, not what would have happened otherwise.</li>
</ol>
<p>Point 3 is the one worth practicing. Most weak data journalism is weak because a change over time is presented as an effect of one particular cause.</p>
</div>
</div>
</div>
</section>
</section>
<section id="what-a-data-science-project-looks-like" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="what-a-data-science-project-looks-like"><span class="header-section-number">1.3</span> What a data science project looks like</h2>
<p>Projects vary, but most of them pass through the same stages.</p>
<div id="11915fd8" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-5-output-1.png" width="577" height="130" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Five of these stages are reasonably self-explanatory. <strong>Modeling</strong> is the exception, and it deserves a definition: modeling means fitting a rule to the data, either in order to summarize a pattern compactly or in order to predict a value that has not been observed. Determining whether a fitted rule means anything at all is a large part of what the second half of this book is concerned with.</p>
<p>The chapters of the book follow these stages in order:</p>
<div id="tbl-workflow-chapters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-workflow-chapters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.2: Where each stage is covered
</figcaption>
<div aria-describedby="tbl-workflow-chapters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Chapters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ask a question</td>
<td>Every chapter starts with one</td>
</tr>
<tr class="even">
<td>Get the data</td>
<td><span class="quarto-unresolved-ref">?sec-data-tables</span>, <a href="web_data.html" class="quarto-xref"><span>Chapter 16</span></a></td>
</tr>
<tr class="odd">
<td>Clean it</td>
<td><span class="quarto-unresolved-ref">?sec-data-tables</span></td>
</tr>
<tr class="even">
<td>Explore and visualize</td>
<td><span class="quarto-unresolved-ref">?sec-descriptive-stats</span>, <span class="quarto-unresolved-ref">?sec-array-computations</span>, <span class="quarto-unresolved-ref">?sec-data-visualization</span>, <a href="interactive_visualizations.html" class="quarto-xref"><span>Chapter 7</span></a>, <a href="maps.html" class="quarto-xref"><span>Chapter 8</span></a></td>
</tr>
<tr class="odd">
<td>Model</td>
<td><a href="statistical_inference.html" class="quarto-xref"><span>Chapter 10</span></a> through <a href="unsupervised_learning.html" class="quarto-xref"><span>Chapter 15</span></a></td>
</tr>
<tr class="even">
<td>Interpret and communicate</td>
<td><a href="statistical_inference.html" class="quarto-xref"><span>Chapter 10</span></a>, <a href="hypothesis_testing.html" class="quarto-xref"><span>Chapter 11</span></a>, <a href="confidence_intervals.html" class="quarto-xref"><span>Chapter 12</span></a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Two chapters sit outside this table because they supply tools used at every stage. <span class="quarto-unresolved-ref">?sec-python-basics</span> teaches enough Python to write any of the code at all, and <a href="iteration_and_functions.html" class="quarto-xref"><span>Chapter 9</span></a> introduces loops and user-defined functions, which are the tools for repeating an analysis and packaging it up for reuse.</p>
<p>The arrows in the diagram run in only one direction, which is a simplification of how the work actually proceeds. Exploring the data frequently reveals that different data is required, or that the question one began with was the wrong question to ask. Cleaning is rarely finished on the first attempt. In practice, most projects pass through this sequence of stages more than once.</p>
</section>
<section id="writing-analyses-others-can-check" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="writing-analyses-others-can-check"><span class="header-section-number">1.4</span> Writing analyses others can check</h2>
<p>An analysis is best understood as an argument, and like any argument it is worth only as much as a reader’s ability to check it. A result presented without the steps that produced it asks to be taken on faith.</p>
<p>Meeting that standard is harder than it sounds. Over the past decade, researchers across many fields have tried to reproduce published findings and repeatedly failed, sometimes because the original work was wrong and often because the description of what was done was not detailed enough to repeat. This came to be called the <strong>replication crisis</strong>. A written summary of an analysis leaves out exactly the details that matter: which rows were dropped, and which version of the data was used.</p>
<p>Donald Knuth proposed a fix for a related problem in the 1980s. He argued that programs should be written to be read by people, with the explanation and the code composed together as a single document <span class="citation" data-cites="knuth1984">(<a href="#ref-knuth1984" role="doc-biblioref"><strong>knuth1984?</strong></a>)</span>. He called this <strong>literate programming</strong>. Applied to data analysis, the idea is that the writing, the code, and the results belong in one document, so that a reader can follow the reasoning and see precisely what produced each number.</p>
<section id="jupyter-notebooks" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="jupyter-notebooks"><span class="header-section-number">1.4.1</span> Jupyter notebooks</h3>
<p>A <strong>Jupyter notebook</strong> is a document built on that idea. It consists of a sequence of cells of two kinds. <strong>Markdown cells</strong> hold text, which is where the explanation, the reasoning, the headings, and any equations belong, while <strong>code cells</strong> hold the code itself. When a code cell is run, its output appears directly beneath it and remains there as part of the document.</p>
<p>Markdown is a plain-text way of marking up formatting. You type <code>## A heading</code> to get a heading and <code>**important**</code> to get bold, and the notebook renders it when you run the cell. The markdown cell in the diagram below shows what you type rather than how it looks once rendered.</p>
<div id="ac942592" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-6-output-1.png" width="555" height="271" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The number in brackets beside a code cell is its <strong>execution count</strong>. The first cell run in a session is labeled <code>[1]</code>, the next <code>[2]</code>, and so on. The count records the order in which the cells were actually executed, which is not necessarily the order in which they appear on the page. This number is worth keeping in mind, because the next section concerns what happens when those two orders disagree.</p>
<p>To run a cell, click on it and press <code>Shift+Enter</code>. You can return to a cell, change it, and run it again as often as you like. That freedom to revise is what makes a notebook well suited to exploring data, and it is also the source of one difficulty that you should understand before encountering it.</p>
</section>
<section id="the-order-cells-run-in" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="the-order-cells-run-in"><span class="header-section-number">1.4.2</span> The order cells run in</h3>
<p>A notebook keeps a running memory of everything you have executed. This memory is called the <strong>kernel</strong>: the Python session sitting behind the notebook. If you define a variable in one cell and run it, that variable exists in the kernel from then on, no matter where the cell sits on the page or whether you later delete it.</p>
<p>This means a notebook that works perfectly for you can fail for anyone else. Suppose you write a cell, run it, then scroll up and edit an earlier cell without re-running the ones below. The notebook on your screen is now telling a story that its own code no longer produces. A reader who opens it and runs the cells from top to bottom gets different results, or an error.</p>
<p>The execution counts are what allow you to detect this situation. If you scroll through a notebook and the brackets read <code>[1]</code>, <code>[7]</code>, <code>[2]</code>, then the cells were not run in the order in which they are written, and the results displayed cannot be trusted.</p>
<p>There is a simple habit that prevents the problem. Before sharing a notebook or submitting one, restart the kernel and run every cell from the top. In JupyterLab this option is <strong>Kernel → Restart Kernel and Run All Cells</strong>, while other notebook tools call it <strong>Restart &amp; Run All</strong>. Doing so clears the kernel’s memory and runs everything in order, exactly as a new reader would. If the notebook produces the same results after that, then it says what it appears to say.</p>
<p>This book is itself written this way, using a system called Quarto that applies the same idea to books. Every figure in these pages was produced by running the code you can see, at the moment the book was last built, and every number quoted in the text was checked against that code. When the chapter says Linda jumped to 5.5% in 1947, that number came out of the data file rather than out of the author’s memory.</p>
<div id="exercise-introduction-cell-order" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>A student writes three cells and runs them from top to bottom:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>prices <span class="op">=</span> [<span class="fl">3.10</span>, <span class="fl">3.25</span>, <span class="fl">3.40</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>average <span class="op">=</span> <span class="bu">sum</span>(prices) <span class="op">/</span> <span class="bu">len</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(average)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The third cell prints <code>3.25</code>. The student then goes back and edits the <em>first</em> cell to read <code>prices = [3.10, 3.25, 3.40, 4.00]</code>, runs only that first cell, and runs the third cell again.</p>
<p>What does the third cell print now? What would a reader see if they opened the notebook fresh and ran all three cells in order?</p>
</div>
</div>
<div id="solution-introduction-cell-order" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The third cell still prints <code>3.25</code>.</p>
<p>Editing and re-running the first cell changed <code>prices</code>, but <code>average</code> was never recomputed. The second cell has not run since the edit, so <code>average</code> still holds the value calculated from the original three prices.</p>
<p>A reader who opened the notebook fresh and ran all three cells in order would see <code>3.4375</code>, the average of the four prices. The student’s notebook shows one number on screen while its code produces another. <code>Restart &amp; Run All</code> would have caught this immediately.</p>
</div>
</div>
</div>
</section>
</section>
<section id="building-on-the-work-of-others" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="building-on-the-work-of-others"><span class="header-section-number">1.5</span> Building on the work of others</h2>
<p>Almost nobody writes a data analysis entirely from scratch. The plot at the start of this chapter took a dozen lines of code, and every one of those lines rested on work done by other people: reading a file in a standard format, holding a table in memory, choosing where to place the axis ticks, and deciding how to draw a line. Written from nothing, that plot would have been a substantial programming project.</p>
<p>All of this is available because Python code can be packaged and shared. Three terms are easy to confuse and are worth separating:</p>
<ul>
<li>A <strong>script</strong> is code written to do one task, run start to finish. Downloading a set of files is a good use for a script.</li>
<li>A <strong>module</strong> is a file of code meant to be reused, loaded by other code rather than run on its own.</li>
<li>A <strong>package</strong>, also called a <strong>library</strong>, is a collection of related modules distributed together.</li>
</ul>
<p>Loading a package into your own code is called <strong>importing</strong> it, and it looks like this:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>That line makes the pandas package available and gives it the short name <code>pd</code>, so that later code can write <code>pd.read_csv(...)</code> instead of the full name. <span class="quarto-unresolved-ref">?sec-python-basics</span> covers how this works. For now the point is only that the line exists, and that most of what this book does follows from it.</p>
<p>Python is not the only language used for this work. R is the other common choice, and it is well suited to statistics and to producing reports. Python’s advantage is that it is a general-purpose programming language that also has strong data packages, so the same language that loads your data can run a website or control an instrument. Either language is a good place to start, and people who do this professionally often use both.</p>
<section id="the-packages-we-will-use" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="the-packages-we-will-use"><span class="header-section-number">1.5.1</span> The packages we will use</h3>
<div id="tbl-packages" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.3: The main packages used in this book
</figcaption>
<div aria-describedby="tbl-packages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>What it does</th>
<th>Where it appears</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Matplotlib</td>
<td>Draws plots</td>
<td><span class="quarto-unresolved-ref">?sec-descriptive-stats</span>, <span class="quarto-unresolved-ref">?sec-data-visualization</span></td>
</tr>
<tr class="even">
<td>NumPy</td>
<td>Arrays of numbers and fast computation on them</td>
<td><span class="quarto-unresolved-ref">?sec-array-computations</span></td>
</tr>
<tr class="odd">
<td>pandas</td>
<td>Data tables: loading, filtering, grouping, joining</td>
<td><span class="quarto-unresolved-ref">?sec-data-tables</span></td>
</tr>
<tr class="even">
<td>seaborn, Plotly</td>
<td>Statistical and interactive graphics</td>
<td><span class="quarto-unresolved-ref">?sec-data-visualization</span>, <a href="interactive_visualizations.html" class="quarto-xref"><span>Chapter 7</span></a></td>
</tr>
<tr class="odd">
<td>GeoPandas</td>
<td>Drawing data onto geographic maps</td>
<td><a href="maps.html" class="quarto-xref"><span>Chapter 8</span></a></td>
</tr>
<tr class="even">
<td>scikit-learn</td>
<td>Machine learning models</td>
<td><a href="classification.html" class="quarto-xref"><span>Chapter 13</span></a> through <a href="unsupervised_learning.html" class="quarto-xref"><span>Chapter 15</span></a></td>
</tr>
<tr class="odd">
<td>Requests, Beautiful Soup</td>
<td>Fetching and reading data from the web</td>
<td><a href="web_data.html" class="quarto-xref"><span>Chapter 16</span></a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>These packages are layered on one another rather than independent. NumPy provides the array of numbers that nearly everything else stores its data in; pandas builds tables on top of NumPy arrays; scikit-learn expects its input as arrays or tables.</p>
<div id="10a6c609" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-7-output-1.png" width="495" height="219" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Every package in that table is free and open source, written and maintained by communities of contributors. These packages also change over time. New versions add features, occasionally rename existing ones, and sometimes break code that previously worked. This is the reason a careful analysis records which versions of each package it used, a point that <span class="quarto-unresolved-ref">?sec-setup</span> returns to.</p>
</section>
<section id="getting-set-up" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="getting-set-up"><span class="header-section-number">1.5.2</span> Getting set up</h3>
<p>Running the code in this book requires three things: Python itself, the packages listed above, and a way to run notebooks. Installing them is a one-time task, and it is the part of learning data science most likely to be frustrating for reasons that have nothing to do with data science.</p>
<p><span class="quarto-unresolved-ref">?sec-setup</span> walks through it with a tool called uv, and also covers the two alternatives you will run into in other courses and workplaces, pip with venv and conda. If you cannot install software on the computer you are using, it covers running notebooks in a browser instead, which requires installing nothing.</p>
<p>Once you have a notebook you can run, the exercise below confirms that everything is connected properly.</p>
<div id="exercise-introduction-first-import" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Open a Jupyter notebook and run the following two lines in a code cell:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.__version__)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>If a version number prints, pandas is installed and your setup works. If you get a <code>ModuleNotFoundError</code> instead, the package is not available in the environment your notebook is using. An environment is the particular Python installation and set of packages your notebook is connected to, and <span class="quarto-unresolved-ref">?sec-setup</span> explains both what that means and how to fix it.</p>
</div>
</div>
<div id="solution-introduction-first-import" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="c88bce37" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.__version__)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>3.0.5</code></pre>
</div>
</div>
<p>Your version number will almost certainly differ from the one shown here, and that is fine. What matters is that a number printed at all.</p>
</div>
</div>
</div>
</section>
</section>
<section id="how-to-use-this-book" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="how-to-use-this-book"><span class="header-section-number">1.6</span> How to use this book</h2>
<p>This book assumes no programming experience and no mathematics beyond arithmetic. You need a computer you can install software on, or failing that, an internet connection and a browser.</p>
<p>Type the code out rather than simply reading it. Programming is a skill that resembles playing an instrument more than it resembles learning a set of facts, and it does not transfer from the page merely by being understood. Once a piece of code runs, change it and see what happens: plot a different name, or break something deliberately and read the error message that results.</p>
<p>Most sections end with an exercise, and every exercise has a solution you can expand. Try the exercise before opening the solution. The difficulty of a problem you have not attempted is impossible to judge, and reading a worked solution produces a feeling of understanding that is not the same thing as understanding.</p>
<p>The chapters are meant to be read in order: later chapters use the tools introduced earlier, and nothing is used before it is taught.</p>
</section>
<section id="summary" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="summary"><span class="header-section-number">1.7</span> Summary</h2>
<ul>
<li><strong>Data science</strong> uses computation and statistical reasoning to answer questions with data. Knowledge of the subject the data is about is part of the job, not an optional extra.</li>
<li>It overlaps heavily with <strong>statistics</strong>. The differences are of emphasis: where the data comes from, how much programming is involved, and whether a method is trusted because of a mathematical guarantee or because it performs well on data it has not seen.</li>
<li>Because data records a world that contains its own biases, a model built on that data can reproduce and spread them. A pattern is also not a cause.</li>
<li>The field became publicly visible through a series of episodes, some of which showed what analyzing data made possible and some of which showed how it fails. Both halves matter.</li>
<li>Most projects move through the same stages: ask a question, get the data, clean it, explore and visualize, model, then interpret and communicate. Expect to go around that loop more than once.</li>
<li><strong>Literate programming</strong> is the practice of writing explanation and code together in one document. <strong>Jupyter notebooks</strong> apply it to data analysis, mixing markdown cells, code cells, and the output of that code.</li>
<li>Because a notebook’s <strong>kernel</strong> remembers everything it has run, cells run out of order can make a notebook show results its own code no longer produces. Restart the kernel and run all cells before sharing one.</li>
<li>A <strong>package</strong> is a collection of reusable code that someone else wrote and shared. Analyses are built on layers of them, and this book uses Matplotlib, NumPy, pandas, scikit-learn, and several others.</li>
</ul>
</section>
<section id="exercises" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="exercises"><span class="header-section-number">1.8</span> Exercises</h2>
<div id="exercise-introduction-your-name" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Return to the code at the start of this chapter and plot your own first name, or the name of someone you know.</p>
<p>Change the list of names in the <code>for</code> line to the name you want, and change <code>"girl"</code> to <code>"boy"</code> if appropriate. Then read off the plot: in what year was the name most popular, and roughly what percentage of babies received it that year?</p>
<p>There are two limitations of the data to be aware of. The records stop in 2008, and they include only the thousand most common names for each sex in each year, so an uncommon name may not appear in them at all.</p>
</div>
</div>
<div id="solution-introduction-your-name" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Only two strings in the original cell need to change. Using “Ethan” as the example:</p>
<div id="14d15a76" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>boys <span class="op">=</span> names[names[<span class="st">"sex"</span>] <span class="op">==</span> <span class="st">"boy"</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> [<span class="st">"Ethan"</span>]:</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    one_name <span class="op">=</span> boys[boys[<span class="st">"name"</span>] <span class="op">==</span> name]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    plt.plot(one_name[<span class="st">"year"</span>], one_name[<span class="st">"percent"</span>] <span class="op">*</span> <span class="dv">100</span>, label<span class="op">=</span>name)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Year"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Percentage of boys given the name"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="introduction_files/figure-html/cell-9-output-1.png" width="590" height="430" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The name sits close to zero for a century and then climbs sharply from the late 1980s, peaking a little above 1% shortly after 2000. Reading that off the plot is all the exercise asked for.</p>
<p>If you want the exact figures rather than an eyeballed estimate, pandas can find them. You are not expected to write this yet; the tools appear in <span class="quarto-unresolved-ref">?sec-data-tables</span>.</p>
<div id="b4ebf2e6" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ethan <span class="op">=</span> boys[boys[<span class="st">"name"</span>] <span class="op">==</span> <span class="st">"Ethan"</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>peak <span class="op">=</span> ethan.loc[ethan[<span class="st">"percent"</span>].idxmax()]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(peak[<span class="st">"year"</span>], <span class="bu">round</span>(peak[<span class="st">"percent"</span>] <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>2002 1.07</code></pre>
</div>
</div>
<p>The peak is 2002, when 1.07% of boys were given the name. Compare that with Mary’s 7.2% in 1880: even a name at the top of its popularity today reaches a small fraction of what a common name reached a century ago.</p>
<p>If nothing plots at all, the name is probably absent from the data because it never reached the top thousand in any year.</p>
</div>
</div>
</div>
<div id="exercise-introduction-your-workflow" class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pick a question you want answered, in any area you care about. Sketch how you would work through the six stages in <a href="#tbl-workflow-chapters" class="quarto-xref">Table&nbsp;<span>1.2</span></a>.</p>
<p>For each stage, write one sentence. Be concrete about the second stage in particular: name the data you would need, and say whether you think it exists and who would have it.</p>
</div>
</div>
<div id="solution-introduction-your-workflow" class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Answers will vary. As a worked example, take the question “are the buses on my route getting less reliable?”</p>
<ol type="1">
<li><strong>Ask a question.</strong> Has the proportion of buses on route 12 arriving more than five minutes late increased over the past three years?</li>
<li><strong>Get the data.</strong> Scheduled and actual arrival times per stop. Many transit agencies publish this; if mine does not, I would have to ask, or record arrivals myself for a period, which would give a much smaller and more limited dataset.</li>
<li><strong>Clean it.</strong> Decide how to treat trips that were cancelled outright, stops that were skipped, and any period where the route itself was changed.</li>
<li><strong>Explore and visualize.</strong> Plot the proportion of late arrivals by month over three years, and look at whether the pattern differs by time of day.</li>
<li><strong>Model.</strong> Estimate the size of the change, and check whether a trend that size could plausibly be produced by chance variation alone.</li>
<li><strong>Interpret and communicate.</strong> Write the result up with the plot, state what the data does not cover, and say plainly whether the change is large enough to matter to a rider.</li>
</ol>
<p>The most common weak point in a sketch like this is stage 2. Questions that are easy to ask are frequently attached to data that nobody collected.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link" aria-label="Welcome">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Welcome</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./python_basics.html" class="pagination-link" aria-label="Python basics">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Python basics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>